<?php

namespace Database\Seeders;

use DateTime;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $timestamp = new DateTime;
        $countries = [
            ['name' => 'Afghanistan', 'alpha2' => 'AF', 'alpha3' => 'AFG', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Aland Islands', 'alpha2' => 'AX', 'alpha3' => 'ALA', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Albania', 'alpha2' => 'AL', 'alpha3' => 'ALB', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Algeria', 'alpha2' => 'DZ', 'alpha3' => 'DZA', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'American Samoa', 'alpha2' => 'AS', 'alpha3' => 'ASM', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Andorra', 'alpha2' => 'AD', 'alpha3' => 'AND', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Angola', 'alpha2' => 'AO', 'alpha3' => 'AGO', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Anguilla', 'alpha2' => 'AI', 'alpha3' => 'AIA', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Antarctica', 'alpha2' => 'AQ', 'alpha3' => 'ATA', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Antigua and Barbuda', 'alpha2' => 'AG', 'alpha3' => 'ATG', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Argentina', 'alpha2' => 'AR', 'alpha3' => 'ARG', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Armenia', 'alpha2' => 'AM', 'alpha3' => 'ARM', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Aruba', 'alpha2' => 'AW', 'alpha3' => 'ABW', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Australia', 'alpha2' => 'AU', 'alpha3' => 'AUS', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Austria', 'alpha2' => 'AT', 'alpha3' => 'AUT', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Azerbaijan', 'alpha2' => 'AZ', 'alpha3' => 'AZE', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Bahamas', 'alpha2' => 'BS', 'alpha3' => 'BHS', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Bahrain', 'alpha2' => 'BH', 'alpha3' => 'BHR', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Bangladesh', 'alpha2' => 'BD', 'alpha3' => 'BGD', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Barbados', 'alpha2' => 'BB', 'alpha3' => 'BRB', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Belarus', 'alpha2' => 'BY', 'alpha3' => 'BLR', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Belgium', 'alpha2' => 'BE', 'alpha3' => 'BEL', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Belize', 'alpha2' => 'BZ', 'alpha3' => 'BLZ', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Benin', 'alpha2' => 'BJ', 'alpha3' => 'BEN', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Bermuda', 'alpha2' => 'BM', 'alpha3' => 'BMU', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Bhutan', 'alpha2' => 'BT', 'alpha3' => 'BTN', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Bolivia', 'alpha2' => 'BO', 'alpha3' => 'BOL', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Bosnia and Herzegovina', 'alpha2' => 'BA', 'alpha3' => 'BIH', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Botswana', 'alpha2' => 'BW', 'alpha3' => 'BWA', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Bouvet Island', 'alpha2' => 'BV', 'alpha3' => 'BVT', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Brazil', 'alpha2' => 'BR', 'alpha3' => 'BRA', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'British Virgin Islands', 'alpha2' => 'VG', 'alpha3' => 'VGB', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'British Indian Ocean Territory', 'alpha2' => 'IO', 'alpha3' => 'IOT', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Brunei Darussalam', 'alpha2' => 'BN', 'alpha3' => 'BRN', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Bulgaria', 'alpha2' => 'BG', 'alpha3' => 'BGR', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Burkina Faso', 'alpha2' => 'BF', 'alpha3' => 'BFA', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Burundi', 'alpha2' => 'BI', 'alpha3' => 'BDI', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Cambodia', 'alpha2' => 'KH', 'alpha3' => 'KHM', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Cameroon', 'alpha2' => 'CM', 'alpha3' => 'CMR', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Canada', 'alpha2' => 'CA', 'alpha3' => 'CAN', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Cape Verde', 'alpha2' => 'CV', 'alpha3' => 'CPV', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Cayman Islands', 'alpha2' => 'KY', 'alpha3' => 'CYM', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Central African Republic', 'alpha2' => 'CF', 'alpha3' => 'CAF', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Chad', 'alpha2' => 'TD', 'alpha3' => 'TCD', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Chile', 'alpha2' => 'CL', 'alpha3' => 'CHL', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'China', 'alpha2' => 'CN', 'alpha3' => 'CHN', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Hong Kong', 'alpha2' => 'HK', 'alpha3' => 'HKG', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Macao', 'alpha2' => 'MO', 'alpha3' => 'MAC', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Christmas Island', 'alpha2' => 'CX', 'alpha3' => 'CXR', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Cocos (Keeling) Islands', 'alpha2' => 'CC', 'alpha3' => 'CCK', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Colombia', 'alpha2' => 'CO', 'alpha3' => 'COL', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Comoros', 'alpha2' => 'KM', 'alpha3' => 'COM', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Congo (Brazzaville)', 'alpha2' => 'CG', 'alpha3' => 'COG', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Congo (Brazzaville)', 'alpha2' => 'CG', 'alpha3' => 'COG', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Congo, (Kinshasa)', 'alpha2' => 'CD', 'alpha3' => 'COD', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Cook Islands', 'alpha2' => 'CK', 'alpha3' => 'COK', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Costa Rica', 'alpha2' => 'CR', 'alpha3' => 'CRI', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Côte d\'Ivoire', 'alpha2' => 'CI', 'alpha3' => 'CIV', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Croatia', 'alpha2' => 'HR', 'alpha3' => 'HRV', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Cuba', 'alpha2' => 'CU', 'alpha3' => 'CUB', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Cyprus', 'alpha2' => 'CY', 'alpha3' => 'CYP', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Czech Republic', 'alpha2' => 'CZ', 'alpha3' => 'CZE', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Denmark', 'alpha2' => 'DK', 'alpha3' => 'DNK', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Djibouti', 'alpha2' => 'DJ', 'alpha3' => 'DJI', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Dominica', 'alpha2' => 'DM', 'alpha3' => 'DMA', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Dominican Republic', 'alpha2' => 'DO', 'alpha3' => 'DOM', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Ecuador', 'alpha2' => 'EC', 'alpha3' => 'ECU', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Egypt', 'alpha2' => 'EG', 'alpha3' => 'EGY', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'El Salvador', 'alpha2' => 'SV', 'alpha3' => 'SLV', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Equatorial Guinea', 'alpha2' => 'GQ', 'alpha3' => 'GNQ', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Eritrea', 'alpha2' => 'ER', 'alpha3' => 'ERI', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Estonia', 'alpha2' => 'EE', 'alpha3' => 'EST', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Ethiopia', 'alpha2' => 'ET', 'alpha3' => 'ETH', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Falkland Islands (Malvinas)', 'alpha2' => 'FK', 'alpha3' => 'FLK', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Faroe Islands', 'alpha2' => 'FO', 'alpha3' => 'FRO', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Fiji', 'alpha2' => 'FJ', 'alpha3' => 'FJI', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Finland', 'alpha2' => 'FI', 'alpha3' => 'FIN', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'France', 'alpha2' => 'FR', 'alpha3' => 'FRA', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'French Guiana', 'alpha2' => 'GF', 'alpha3' => 'GUF', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'French Polynesia', 'alpha2' => 'PF', 'alpha3' => 'PYF', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'French Southern Territories', 'alpha2' => 'TF', 'alpha3' => 'ATF', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Gabon', 'alpha2' => 'GA', 'alpha3' => 'GAB', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Gambia', 'alpha2' => 'GM', 'alpha3' => 'GMB', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Georgia', 'alpha2' => 'GE', 'alpha3' => 'GEO', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Germany', 'alpha2' => 'DE', 'alpha3' => 'DEU', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Ghana', 'alpha2' => 'GH', 'alpha3' => 'GHA', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Gibraltar', 'alpha2' => 'GI', 'alpha3' => 'GIB', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Greece', 'alpha2' => 'GR', 'alpha3' => 'GRC', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Greenland', 'alpha2' => 'GL', 'alpha3' => 'GRL', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Grenada', 'alpha2' => 'GD', 'alpha3' => 'GRD', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Guadeloupe', 'alpha2' => 'GP', 'alpha3' => 'GLP', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Guam', 'alpha2' => 'GU', 'alpha3' => 'GUM', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Guatemala', 'alpha2' => 'GT', 'alpha3' => 'GTM', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Guernsey', 'alpha2' => 'GG', 'alpha3' => 'GGY', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Guinea', 'alpha2' => 'GN', 'alpha3' => 'GIN', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Guinea-Bissau', 'alpha2' => 'GW', 'alpha3' => 'GNB', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Guyana', 'alpha2' => 'GY', 'alpha3' => 'GUY', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Haiti', 'alpha2' => 'HT', 'alpha3' => 'HTI', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Heard and Mcdonald Islands', 'alpha2' => 'HM', 'alpha3' => 'HMD', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Holy See (Vatican City State)', 'alpha2' => 'VA', 'alpha3' => 'VAT', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Honduras', 'alpha2' => 'HN', 'alpha3' => 'HND', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Hungary', 'alpha2' => 'HU', 'alpha3' => 'HUN', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Iceland', 'alpha2' => 'IS', 'alpha3' => 'ISL', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'India', 'alpha2' => 'IN', 'alpha3' => 'IND', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Indonesia', 'alpha2' => 'ID', 'alpha3' => 'IDN', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Iran, Islamic Republic of', 'alpha2' => 'IR', 'alpha3' => 'IRN', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Iraq', 'alpha2' => 'IQ', 'alpha3' => 'IRQ', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Ireland', 'alpha2' => 'IE', 'alpha3' => 'IRL', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Isle of Man', 'alpha2' => 'IM', 'alpha3' => 'IMN', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Israel', 'alpha2' => 'IL', 'alpha3' => 'ISR', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Italy', 'alpha2' => 'IT', 'alpha3' => 'ITA', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Jamaica', 'alpha2' => 'JM', 'alpha3' => 'JAM', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Japan', 'alpha2' => 'JP', 'alpha3' => 'JPN', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Jersey', 'alpha2' => 'JE', 'alpha3' => 'JEY', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Jordan', 'alpha2' => 'JO', 'alpha3' => 'JOR', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Kazakhstan', 'alpha2' => 'KZ', 'alpha3' => 'KAZ', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Kenya', 'alpha2' => 'KE', 'alpha3' => 'KEN', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Kiribati', 'alpha2' => 'KI', 'alpha3' => 'KIR', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Kiribati', 'alpha2' => 'KI', 'alpha3' => 'KIR', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Korea (North)', 'alpha2' => 'KP', 'alpha3' => 'PRK', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Korea (South)', 'alpha2' => 'KR', 'alpha3' => 'KOR', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Kuwait', 'alpha2' => 'KW', 'alpha3' => 'KWT', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Kyrgyzstan', 'alpha2' => 'KG', 'alpha3' => 'KGZ', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Lao PDR', 'alpha2' => 'LA', 'alpha3' => 'LAO', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Latvia', 'alpha2' => 'LV', 'alpha3' => 'LVA', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Lebanon', 'alpha2' => 'LB', 'alpha3' => 'LBN', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Lesotho', 'alpha2' => 'LS', 'alpha3' => 'LSO', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Liberia', 'alpha2' => 'LR', 'alpha3' => 'LBR', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Libya', 'alpha2' => 'LY', 'alpha3' => 'LBY', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Liechtenstein', 'alpha2' => 'LI', 'alpha3' => 'LIE', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Lithuania', 'alpha2' => 'LT', 'alpha3' => 'LTU', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Luxembourg', 'alpha2' => 'LU', 'alpha3' => 'LUX', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Macedonia, Republic of', 'alpha2' => 'MK', 'alpha3' => 'MKD', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Madagascar', 'alpha2' => 'MG', 'alpha3' => 'MDG', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Malawi', 'alpha2' => 'MW', 'alpha3' => 'MWI', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Malaysia', 'alpha2' => 'MY', 'alpha3' => 'MYS', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Maldives', 'alpha2' => 'MV', 'alpha3' => 'MDV', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Mali', 'alpha2' => 'ML', 'alpha3' => 'MLI', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Malta', 'alpha2' => 'MT', 'alpha3' => 'MLT', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Marshall Islands', 'alpha2' => 'MH', 'alpha3' => 'MHL', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Martinique', 'alpha2' => 'MQ', 'alpha3' => 'MTQ', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Mauritania', 'alpha2' => 'MR', 'alpha3' => 'MRT', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Mauritius', 'alpha2' => 'MU', 'alpha3' => 'MUS', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Mayotte', 'alpha2' => 'YT', 'alpha3' => 'MYT', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Mexico', 'alpha2' => 'MX', 'alpha3' => 'MEX', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Micronesia, Federated States of ', 'alpha2' => 'FM', 'alpha3' => 'FSM', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Moldova', 'alpha2' => 'MD', 'alpha3' => 'MDA', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Monaco', 'alpha2' => 'MC', 'alpha3' => 'MCO', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Mongolia', 'alpha2' => 'MN', 'alpha3' => 'MNG', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Montenegro', 'alpha2' => 'ME', 'alpha3' => 'MNE', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Montserrat', 'alpha2' => 'MS', 'alpha3' => 'MSR', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Morocco', 'alpha2' => 'MA', 'alpha3' => 'MAR', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Mozambique', 'alpha2' => 'MZ', 'alpha3' => 'MOZ', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Myanmar', 'alpha2' => 'MM', 'alpha3' => 'MMR', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Namibia', 'alpha2' => 'NA', 'alpha3' => 'NAM', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Nauru', 'alpha2' => 'NR', 'alpha3' => 'NRU', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Nepal', 'alpha2' => 'NP', 'alpha3' => 'NPL', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Netherlands', 'alpha2' => 'NL', 'alpha3' => 'NLD', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Netherlands Antilles', 'alpha2' => 'AN', 'alpha3' => 'ANT', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'New Caledonia', 'alpha2' => 'NC', 'alpha3' => 'NCL', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'New Zealand', 'alpha2' => 'NZ', 'alpha3' => 'NZL', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Nicaragua', 'alpha2' => 'NI', 'alpha3' => 'NIC', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Niger', 'alpha2' => 'NE', 'alpha3' => 'NER', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Nigeria', 'alpha2' => 'NG', 'alpha3' => 'NGA', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Niue', 'alpha2' => 'NU', 'alpha3' => 'NIU', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Norfolk Island', 'alpha2' => 'NF', 'alpha3' => 'NFK', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Northern Mariana Islands', 'alpha2' => 'MP', 'alpha3' => 'MNP', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Norway', 'alpha2' => 'NO', 'alpha3' => 'NOR', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Oman', 'alpha2' => 'OM', 'alpha3' => 'OMN', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Pakistan', 'alpha2' => 'PK', 'alpha3' => 'PAK', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Palau', 'alpha2' => 'PW', 'alpha3' => 'PLW', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Palestinian Territory', 'alpha2' => 'PS', 'alpha3' => 'PSE', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Panama', 'alpha2' => 'PA', 'alpha3' => 'PAN', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Papua New Guinea', 'alpha2' => 'PG', 'alpha3' => 'PNG', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Paraguay', 'alpha2' => 'PY', 'alpha3' => 'PRY', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Peru', 'alpha2' => 'PE', 'alpha3' => 'PER', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Philippines', 'alpha2' => 'PH', 'alpha3' => 'PHL', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Pitcairn', 'alpha2' => 'PN', 'alpha3' => 'PCN', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Poland', 'alpha2' => 'PL', 'alpha3' => 'POL', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Portugal', 'alpha2' => 'PT', 'alpha3' => 'PRT', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Puerto Rico', 'alpha2' => 'PR', 'alpha3' => 'PRI', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Qatar', 'alpha2' => 'QA', 'alpha3' => 'QAT', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Réunion', 'alpha2' => 'RE', 'alpha3' => 'REU', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Romania', 'alpha2' => 'RO', 'alpha3' => 'ROU', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Russian Federation', 'alpha2' => 'RU', 'alpha3' => 'RUS', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Rwanda', 'alpha2' => 'RW', 'alpha3' => 'RWA', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Saint-Barthélemy', 'alpha2' => 'BL', 'alpha3' => 'BLM', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Saint Helena', 'alpha2' => 'SH', 'alpha3' => 'SHN', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Saint Kitts and Nevis', 'alpha2' => 'KN', 'alpha3' => 'KNA', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Saint Lucia', 'alpha2' => 'LC', 'alpha3' => 'LCA', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Saint-Martin (French part)', 'alpha2' => 'MF', 'alpha3' => 'MAF', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Saint Pierre and Miquelon', 'alpha2' => 'PM', 'alpha3' => 'SPM', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Saint Vincent and Grenadines', 'alpha2' => 'VC', 'alpha3' => 'VCT', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Samoa', 'alpha2' => 'WS', 'alpha3' => 'WSM', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'San Marino', 'alpha2' => 'SM', 'alpha3' => 'SMR', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Sao Tome and Principe', 'alpha2' => 'ST', 'alpha3' => 'STP', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Saudi Arabia', 'alpha2' => 'SA', 'alpha3' => 'SAU', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Senegal', 'alpha2' => 'SN', 'alpha3' => 'SEN', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Serbia', 'alpha2' => 'RS', 'alpha3' => 'SRB', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Seychelles', 'alpha2' => 'SC', 'alpha3' => 'SYC', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Sierra Leone', 'alpha2' => 'SL', 'alpha3' => 'SLE', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Singapore', 'alpha2' => 'SG', 'alpha3' => 'SGP', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Slovakia', 'alpha2' => 'SK', 'alpha3' => 'SVK', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Slovenia', 'alpha2' => 'SI', 'alpha3' => 'SVN', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Solomon Islands', 'alpha2' => 'SB', 'alpha3' => 'SLB', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Somalia', 'alpha2' => 'SO', 'alpha3' => 'SOM', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'South Africa', 'alpha2' => 'ZA', 'alpha3' => 'ZAF', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'South Georgia and the South Sandwich Islands', 'alpha2' => 'GS', 'alpha3' => 'SGS', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'South Sudan', 'alpha2' => 'SS', 'alpha3' => 'SSD', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Spain', 'alpha2' => 'ES', 'alpha3' => 'ESP', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Sri Lanka', 'alpha2' => 'LK', 'alpha3' => 'LKA', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Sudan', 'alpha2' => 'SD', 'alpha3' => 'SDN', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Suriname', 'alpha2' => 'SR', 'alpha3' => 'SUR', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Svalbard and Jan Mayen Islands', 'alpha2' => 'SJ', 'alpha3' => 'SJM', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Swaziland', 'alpha2' => 'SZ', 'alpha3' => 'SWZ', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Sweden', 'alpha2' => 'SE', 'alpha3' => 'SWE', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Switzerland', 'alpha2' => 'CH', 'alpha3' => 'CHE', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Syrian Arab Republic (Syria)', 'alpha2' => 'SY', 'alpha3' => 'SYR', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Taiwan, Republic of China', 'alpha2' => 'TW', 'alpha3' => 'TWN', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Tajikistan', 'alpha2' => 'TJ', 'alpha3' => 'TJK', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Tanzania, United Republic of', 'alpha2' => 'TZ', 'alpha3' => 'TZA', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Thailand', 'alpha2' => 'TH', 'alpha3' => 'THA', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Timor-Leste', 'alpha2' => 'TL', 'alpha3' => 'TLS', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Togo', 'alpha2' => 'TG', 'alpha3' => 'TGO', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Tokelau', 'alpha2' => 'TK', 'alpha3' => 'TKL', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Tonga', 'alpha2' => 'TO', 'alpha3' => 'TON', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Trinidad and Tobago', 'alpha2' => 'TT', 'alpha3' => 'TTO', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Tunisia', 'alpha2' => 'TN', 'alpha3' => 'TUN', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Turkey', 'alpha2' => 'TR', 'alpha3' => 'TUR', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Turkmenistan', 'alpha2' => 'TM', 'alpha3' => 'TKM', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Turks and Caicos Islands', 'alpha2' => 'TC', 'alpha3' => 'TCA', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Tuvalu', 'alpha2' => 'TV', 'alpha3' => 'TUV', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Uganda', 'alpha2' => 'UG', 'alpha3' => 'UGA', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Ukraine', 'alpha2' => 'UA', 'alpha3' => 'UKR', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'United Arab Emirates', 'alpha2' => 'AE', 'alpha3' => 'ARE', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'United Kingdom', 'alpha2' => 'GB', 'alpha3' => 'GBR', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'United States', 'alpha2' => 'US', 'alpha3' => 'USA', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'US Minor Outlying Islands', 'alpha2' => 'UM', 'alpha3' => 'UMI', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Uruguay', 'alpha2' => 'UY', 'alpha3' => 'URY', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Uzbekistan', 'alpha2' => 'UZ', 'alpha3' => 'UZB', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Vanuatu', 'alpha2' => 'VU', 'alpha3' => 'VUT', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Venezuela (Bolivarian Republic)', 'alpha2' => 'VE', 'alpha3' => 'VEN', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Viet Nam', 'alpha2' => 'VN', 'alpha3' => 'VNM', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Virgin Islands, US', 'alpha2' => 'VI', 'alpha3' => 'VIR', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Wallis and Futuna Islands', 'alpha2' => 'WF', 'alpha3' => 'WLF', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Western Sahara', 'alpha2' => 'EH', 'alpha3' => 'ESH', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Yemen', 'alpha2' => 'YE', 'alpha3' => 'YEM', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Zambia', 'alpha2' => 'ZM', 'alpha3' => 'ZMB', 'created_at' => $timestamp, 'updated_at' => $timestamp],
            ['name' => 'Zimbabwe', 'alpha2' => 'ZW', 'alpha3' => 'ZWE', 'created_at' => $timestamp, 'updated_at' => $timestamp],
        ];

        DB::table('countries')->insert($countries);
    }
}
