<?php

namespace Database\Seeders;

use App\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RetailersTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        function checkAccountManager($email)
        {
            $user = User::where('email', $email)->select('id')->first();

            return optional($user)->id;
        }

        DB::table('retailers')->delete();

        // Addresses
        DB::table('addresses')->insert([
            0 => [
                'addressable_type' => 'App\\Models\\Retailer',
                'addressable_id' => 1,
                'address' => '320 Don Hillock Drive',
                'address2' => '',
                'city' => 'Aurora',
                'province' => 'Ontario',
                'postal_code' => 'L4G 0G9',
                'country_id' => 40,
                'cloned_from_id' => null,
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
            ],
            1 => [
                'addressable_type' => 'App\\Models\\Retailer',
                'addressable_id' => 2,
                'address' => '6120 - 1A Street S.W',
                'address2' => '',
                'city' => 'Calgary',
                'province' => 'AB',
                'postal_code' => 'T2H 0G3',
                'country_id' => 40,
                'cloned_from_id' => null,
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
            ],
            2 => [
                'addressable_type' => 'App\\Models\\Retailer',
                'addressable_id' => 3,
                'address' => '85 Ellesmere Road',
                'address2' => '',
                'city' => 'Scarborough',
                'province' => 'ON',
                'postal_code' => 'M1R 4B7',
                'country_id' => 40,
                'cloned_from_id' => null,
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
            ],
            3 => [
                'addressable_type' => 'App\\Models\\Retailer',
                'addressable_id' => 4,
                'address' => '58 Antares Drive',
                'address2' => 'Unit #1',
                'city' => 'Nepean',
                'province' => 'ON',
                'postal_code' => 'K2E 7W6',
                'country_id' => 40,
                'cloned_from_id' => null,
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
            ],
            4 => [
                'addressable_type' => 'App\\Models\\Retailer',
                'addressable_id' => 6,
                'address' => '1 President',
                'address2' => '',
                'city' => 'Brampton',
                'province' => 'Ontario',
                'postal_code' => 'L6Y 5S5',
                'country_id' => 40,
                'cloned_from_id' => null,
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
            ],
            5 => [
                'addressable_type' => 'App\\Models\\Retailer',
                'addressable_id' => 7,
                'address' => '1 President',
                'address2' => '',
                'city' => 'Brampton',
                'province' => 'Ontario',
                'postal_code' => 'L6Y 5S5',
                'country_id' => 40,
                'cloned_from_id' => null,
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
            ],
            6 => [
                'addressable_type' => 'App\\Models\\Retailer',
                'addressable_id' => 12,
                'address' => '243 Consumers Rd.',
                'address2' => '',
                'city' => 'Toronto',
                'province' => 'Ontario',
                'postal_code' => 'M2J 4W8',
                'country_id' => 40,
                'cloned_from_id' => null,
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
            ],
            7 => [
                'addressable_type' => 'App\\Models\\Retailer',
                'addressable_id' => 13,
                'address' => '1 Wilkinson Road',
                'address2' => '',
                'city' => 'Brampton',
                'province' => 'Ontario',
                'postal_code' => 'L6T 4M6',
                'country_id' => 40,
                'cloned_from_id' => null,
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
            ],
            8 => [
                'addressable_type' => 'App\\Models\\Retailer',
                'addressable_id' => 16,
                'address' => '2101 91st Street',
                'address2' => '',
                'city' => 'North Bergen',
                'province' => 'NJ',
                'postal_code' => '07047',
                'country_id' => 237,
                'cloned_from_id' => null,
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
            ],
            9 => [
                'addressable_type' => 'App\\Models\\Retailer',
                'addressable_id' => 17,
                'address' => '1940 Argentia Road',
                'address2' => '',
                'city' => 'Mississauga',
                'province' => 'Ontario',
                'postal_code' => 'L5N 1P9',
                'country_id' => 40,
                'cloned_from_id' => null,
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
            ],
            10 => [
                'addressable_type' => 'App\\Models\\Retailer',
                'addressable_id' => 19,
                'address' => '904 The East Mall',
                'address2' => '2nd floor',
                'city' => 'Toronto',
                'province' => 'Ontario',
                'postal_code' => 'M9B 6K2',
                'country_id' => 40,
                'cloned_from_id' => null,
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
            ],
            11 => [
                'addressable_type' => 'App\\Models\\Retailer',
                'addressable_id' => 20,
                'address' => '2285 West 4th Avenue',
                'address2' => '2nd Level',
                'city' => 'Vancouver',
                'province' => 'British Columbia',
                'postal_code' => 'V6K 1N9',
                'country_id' => 40,
                'cloned_from_id' => null,
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
            ],
        ]);

        // Retailers
        DB::table('retailers')->insert([
            0 => [
                'name' => 'Bulk Barn',
                'number_stores' => 269,
                'fiscal_year_start' => null,
                'account_manager_id' => checkAccountManager('mchapman@puritylife.com'),
                'distribution_type' => 'Cross Dock',
                'markup' => '0.26',
                'target_margin' => '0.26',
                'as400_pricing_file' => 'BULKBARN',
                'costing_type' => 'warehouse',
                'warehouse_number' => '01',
                'allow_promos' => 0,
                'websites' => null,
                'state' => 1,
                'created_at' => '2020-11-04 13:39:51',
                'updated_at' => '2020-11-04 13:39:51',
                'deleted_at' => null,
            ],
            1 => [
                'name' => 'Community Natural Foods',
                'number_stores' => null,
                'fiscal_year_start' => null,
                'account_manager_id' => null,
                'distribution_type' => '',
                'markup' => '0.18',
                'target_margin' => '0.15',
                'as400_pricing_file' => 'CNF',
                'costing_type' => 'landed',
                'warehouse_number' => '04',
                'allow_promos' => 0,
                'websites' => null,
                'state' => 1,
                'created_at' => '2020-11-04 13:39:51',
                'updated_at' => '2020-11-04 13:39:51',
                'deleted_at' => null,
            ],
            2 => [
                'name' => 'Healthy Planet',
                'number_stores' => 2,
                'fiscal_year_start' => null,
                'account_manager_id' => null,
                'distribution_type' => '',
                'markup' => '0.17',
                'target_margin' => '0.22',
                'as400_pricing_file' => 'PLANET',
                'costing_type' => 'landed',
                'warehouse_number' => '01',
                'allow_promos' => 0,
                'websites' => null,
                'state' => 1,
                'created_at' => '2020-11-04 13:39:51',
                'updated_at' => '2020-11-04 13:39:51',
                'deleted_at' => null,
            ],
            3 => [
                'name' => 'Kardish Food',
                'number_stores' => 4,
                'fiscal_year_start' => null,
                'account_manager_id' => null,
                'distribution_type' => ' CALCULATED BASED ON COST + PRICE / 0.81 (19%)',
                'markup' => '0.19',
                'target_margin' => '0.22',
                'as400_pricing_file' => 'KARDISH',
                'costing_type' => 'landed',
                'warehouse_number' => '01',
                'allow_promos' => 0,
                'websites' => null,
                'state' => 1,
                'created_at' => '2020-11-04 13:39:51',
                'updated_at' => '2020-11-04 13:39:51',
                'deleted_at' => null,
            ],
            4 => [
                'name' => 'Loblaw',
                'number_stores' => 280,
                'fiscal_year_start' => null,
                'account_manager_id' => checkAccountManager('julie@puritylife.com'),
                'distribution_type' => '',
                'markup' => '0.22',
                'target_margin' => '0.22',
                'as400_pricing_file' => 'WFM-COST',
                'costing_type' => 'warehouse',
                'warehouse_number' => '01',
                'allow_promos' => 0,
                'websites' => null,
                'state' => 1,
                'created_at' => '2020-11-04 13:39:51',
                'updated_at' => '2020-11-04 13:39:51',
                'deleted_at' => null,
            ],
            5 => [
                'name' => 'Loblaw Pharmacy',
                'number_stores' => null,
                'fiscal_year_start' => null,
                'account_manager_id' => null,
                'distribution_type' => '',
                'markup' => '0.22',
                'target_margin' => '0.22',
                'as400_pricing_file' => 'WFM-COST',
                'costing_type' => 'warehouse',
                'warehouse_number' => '01',
                'allow_promos' => 0,
                'websites' => null,
                'state' => 1,
                'created_at' => '2020-11-04 13:39:51',
                'updated_at' => '2020-11-04 13:39:51',
                'deleted_at' => null,
            ],
            6 => [
                'name' => 'Natural Value',
                'number_stores' => null,
                'fiscal_year_start' => null,
                'account_manager_id' => checkAccountManager('julie@puritylife.com'),
                'distribution_type' => 'DC',
                'markup' => '0.22',
                'target_margin' => '0.22',
                'as400_pricing_file' => 'WFM-COST',
                'costing_type' => 'warehouse',
                'warehouse_number' => '01',
                'allow_promos' => 0,
                'websites' => null,
                'state' => 1,
                'created_at' => '2020-11-04 13:39:51',
                'updated_at' => '2020-11-04 13:39:51',
                'deleted_at' => null,
            ],
            7 => [
                'name' => 'Natures Emporium',
                'number_stores' => null,
                'fiscal_year_start' => null,
                'account_manager_id' => null,
                'distribution_type' => '',
                'markup' => '0.18',
                'target_margin' => '0.15',
                'as400_pricing_file' => 'NATEMP',
                'costing_type' => 'landed',
                'warehouse_number' => '01',
                'allow_promos' => 0,
                'websites' => null,
                'state' => 1,
                'created_at' => '2020-11-04 13:39:51',
                'updated_at' => '2020-11-04 13:39:51',
                'deleted_at' => null,
            ],
            8 => [
                'name' => 'Nature\'s Fare',
                'number_stores' => null,
                'fiscal_year_start' => null,
                'account_manager_id' => checkAccountManager('brian@puritylife.com'),
                'distribution_type' => '',
                'markup' => '0.00',
                'target_margin' => '0.22',
                'as400_pricing_file' => 'FARE',
                'costing_type' => 'landed',
                'warehouse_number' => '01',
                'allow_promos' => 1,
                'websites' => null,
                'state' => 1,
                'created_at' => '2020-11-04 13:39:51',
                'updated_at' => '2020-11-04 13:39:51',
                'deleted_at' => null,
            ],
            9 => [
                'name' => 'Planet Organic',
                'number_stores' => null,
                'fiscal_year_start' => null,
                'account_manager_id' => null,
                'distribution_type' => '',
                'markup' => '0.18',
                'target_margin' => '0.22',
                'as400_pricing_file' => 'PLORG',
                'costing_type' => 'landed',
                'warehouse_number' => '01',
                'allow_promos' => 0,
                'websites' => null,
                'state' => 1,
                'created_at' => '2020-11-04 13:39:51',
                'updated_at' => '2020-11-04 13:39:51',
                'deleted_at' => null,
            ],
            10 => [
                'name' => 'Popeyes® Supplements Canada',
                'number_stores' => null,
                'fiscal_year_start' => null,
                'account_manager_id' => checkAccountManager('mchapman@puritylife.com'),
                'distribution_type' => '',
                'markup' => '0.15',
                'target_margin' => '0.15',
                'as400_pricing_file' => 'POPEYES',
                'costing_type' => 'landed',
                'warehouse_number' => '01',
                'allow_promos' => 0,
                'websites' => null,
                'state' => 1,
                'created_at' => '2020-11-04 13:39:51',
                'updated_at' => '2020-11-04 13:39:51',
                'deleted_at' => null,
            ],
            11 => [
                'name' => 'Shoppers Drugmart',
                'number_stores' => 950,
                'fiscal_year_start' => '2020-01-01',
                'account_manager_id' => null,
                'distribution_type' => 'Ship to 3-4 Matrix locations-Moncton, Mississauga, Cornwall and Calgary who in turn ships to all stores',
                'markup' => '0.22',
                'target_margin' => '0.22',
                'as400_pricing_file' => 'SHOPPERS',
                'costing_type' => 'warehouse',
                'warehouse_number' => '01',
                'allow_promos' => 0,
                'websites' => null,
                'state' => 1,
                'created_at' => '2020-11-04 13:39:51',
                'updated_at' => '2020-11-04 13:39:51',
                'deleted_at' => null,
            ],
            12 => [
                'name' => 'Showcase',
                'number_stores' => 119,
                'fiscal_year_start' => null,
                'account_manager_id' => checkAccountManager('mchapman@puritylife.com'),
                'distribution_type' => '',
                'markup' => '0.01',
                'target_margin' => '0.22',
                'as400_pricing_file' => 'SHOWCASE',
                'costing_type' => 'warehouse',
                'warehouse_number' => '01',
                'allow_promos' => 0,
                'websites' => null,
                'state' => 1,
                'created_at' => '2020-11-04 13:39:51',
                'updated_at' => '2020-11-04 13:39:51',
                'deleted_at' => null,
            ],
            13 => [
                'name' => 'Sobeys West',
                'number_stores' => null,
                'fiscal_year_start' => null,
                'account_manager_id' => null,
                'distribution_type' => '',
                'markup' => '0.22',
                'target_margin' => '0.22',
                'as400_pricing_file' => 'SOBEYS-W',
                'costing_type' => 'warehouse',
                'warehouse_number' => '01',
                'allow_promos' => 0,
                'websites' => null,
                'state' => 1,
                'created_at' => '2020-11-04 13:39:51',
                'updated_at' => '2020-11-04 13:39:51',
                'deleted_at' => null,
            ],
            14 => [
                'name' => 'Vita Path',
                'number_stores' => 3,
                'fiscal_year_start' => null,
                'account_manager_id' => checkAccountManager('mchapman@puritylife.com'),
                'distribution_type' => 'Direct to Store',
                'markup' => '0.28',
                'target_margin' => '0.22',
                'as400_pricing_file' => 'VITAPATH',
                'costing_type' => 'warehouse',
                'warehouse_number' => '01',
                'allow_promos' => 0,
                'websites' => null,
                'state' => 1,
                'created_at' => '2020-11-04 13:39:51',
                'updated_at' => '2020-11-04 13:39:51',
                'deleted_at' => null,
            ],
            15 => [
                'name' => 'Walmart',
                'number_stores' => 335,
                'fiscal_year_start' => '2020-02-01',
                'account_manager_id' => null,
                'distribution_type' => '',
                'markup' => '0.22',
                'target_margin' => '0.22',
                'as400_pricing_file' => 'WALMART',
                'costing_type' => 'warehouse',
                'warehouse_number' => '01',
                'allow_promos' => 0,
                'websites' => null,
                'state' => 1,
                'created_at' => '2020-11-04 13:39:51',
                'updated_at' => '2020-11-04 13:39:51',
                'deleted_at' => null,
            ],
            16 => [
                'name' => 'Well.ca',
                'number_stores' => null,
                'fiscal_year_start' => null,
                'account_manager_id' => null,
                'distribution_type' => '',
                'markup' => null,
                'target_margin' => '0.22',
                'as400_pricing_file' => 'WELL.CA',
                'costing_type' => 'landed',
                'warehouse_number' => '01',
                'allow_promos' => 0,
                'websites' => null,
                'state' => 1,
                'created_at' => '2020-11-04 13:39:51',
                'updated_at' => '2020-11-04 13:39:51',
                'deleted_at' => null,
            ],
            17 => [
                'name' => 'Whole Foods East',
                'number_stores' => 6,
                'fiscal_year_start' => '2020-09-01',
                'account_manager_id' => checkAccountManager('mchapman@puritylife.com'),
                'distribution_type' => 'Purity Life Direct to store.',
                'markup' => '0.11',
                'target_margin' => '0.10',
                'as400_pricing_file' => 'WFM-COST',
                'costing_type' => 'landed',
                'warehouse_number' => '01',
                'allow_promos' => 1,
                'websites' => null,
                'state' => 1,
                'created_at' => '2020-11-04 13:39:51',
                'updated_at' => '2020-11-04 13:39:51',
                'deleted_at' => null,
            ],
            18 => [
                'name' => 'Whole Foods Market - West',
                'number_stores' => 7,
                'fiscal_year_start' => '2020-09-01',
                'account_manager_id' => checkAccountManager('mchapman@puritylife.com'),
                'distribution_type' => 'Purity Life Direct to Store',
                'markup' => '0.11',
                'target_margin' => '0.10',
                'as400_pricing_file' => 'WFM-WEST',
                'costing_type' => 'landed',
                'warehouse_number' => '01',
                'allow_promos' => 1,
                'websites' => null,
                'state' => 1,
                'created_at' => '2020-11-04 13:39:51',
                'updated_at' => '2020-11-04 13:39:51',
                'deleted_at' => null,
            ],
        ]);

        // Contacts
        $retailerContacts = [
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 1,
                'role' => 'Buyer',
                'name' => 'Brent Pallett',
                'position' => null,
                'email' => 'brentpallett@bulkbarn.ca',
                'phone' => '905-726-5000 ext. 8340',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 1,
                'role' => 'Buyer',
                'name' => 'Lacey Carter',
                'position' => null,
                'email' => 'LaceyCarter@bulkbarn.ca',
                'phone' => '905-726-5000 ext. 8352',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 4,
                'role' => 'Buyer',
                'name' => 'ANNE PILON',
                'position' => null,
                'email' => '',
                'phone' => '',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 4,
                'role' => 'Other',
                'name' => 'KIM KLAUSEN',
                'position' => null,
                'email' => '',
                'phone' => '',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 6,
                'role' => 'Buyer',
                'name' => 'Franca Contardo',
                'position' => 'Cough/Smoke/Eyes',
                'email' => 'franca.contardo@loblaw.ca',
                'phone' => '905.459.2500 ext 616571',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 6,
                'role' => 'Buyer',
                'name' => 'Steve Bernard',
                'position' => 'Diet/Multi Vitamins',
                'email' => 'steven.bernard@loblaw.ca',
                'phone' => '905.459.2500 ext 6728',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 6,
                'role' => 'Buyer',
                'name' => 'Slavika Kacaverik',
                'position' => 'Oral Care',
                'email' => 'slavika.kacaverik@loblaw.ca',
                'phone' => '905.459.2500',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 6,
                'role' => 'Other',
                'name' => 'Adwin Simpson',
                'position' => 'Steve Bernard assistant',
                'email' => 'Adwin.simpson@loblaw.ca',
                'phone' => '',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 6,
                'role' => 'Other',
                'name' => 'Cheryl Sultana',
                'position' => 'Franca assistant',
                'email' => 'cheryl.sultana@loblaw.ca',
                'phone' => '',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 7,
                'role' => 'Buyer',
                'name' => 'Aaron Skelton',
                'position' => 'Food',
                'email' => 'Jill.Rudderham@loblaw.ca',
                'phone' => '905.459.2500 ext 616294',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 7,
                'role' => 'Buyer',
                'name' => 'Shaun Kernaghan',
                'position' => 'Supplements/NPC',
                'email' => 'shaun.kernaghan@loblaw.ca',
                'phone' => '905.459.2500 ext 616294',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 7,
                'role' => 'Other',
                'name' => 'Brenda Fontes',
                'position' => 'Senior Merchandising Manager Fortinos',
                'email' => 'brenda.fontes@loblaw.ca',
                'phone' => '905.383.5445 ext 3232',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 7,
                'role' => 'Other',
                'name' => 'Laura Usher',
                'position' => 'Merchant',
                'email' => 'laura.usher@loblaw.ca',
                'phone' => '905.459.2500 ext 616955',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 7,
                'role' => 'Other',
                'name' => 'Izabella Shaker',
                'position' => 'Associate Merchant',
                'email' => '',
                'phone' => '',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 7,
                'role' => 'Other',
                'name' => 'Francisca Noegroho',
                'position' => 'Associate Merchant',
                'email' => 'francisca.noegroho@loblaw.ca',
                'phone' => '905.459.2500 ext 616688',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 7,
                'role' => 'Other',
                'name' => 'Sharon Rice',
                'position' => 'Assistant Category Manager',
                'email' => 'sharon.rice@loblaw.ca',
                'phone' => '905.459.2500 ext 615938',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 7,
                'role' => 'Other',
                'name' => 'Elizabeth Crawley',
                'position' => 'Director - Natural Value',
                'email' => '',
                'phone' => '905-459-2500 ext 615631',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 12,
                'role' => 'Buyer',
                'name' => 'Cecilia Fiorino',
                'position' => 'Hair Care',
                'email' => 'CFiorino@shoppersdrugmart.ca',
                'phone' => '(416) 490-2649',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 12,
                'role' => 'Buyer',
                'name' => 'Lian Ellis',
                'position' => 'NHP/ Cough & Cold/Fem Care',
                'email' => 'LEllis@shoppersdrugmart.ca',
                'phone' => '(416) 490-2706',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 12,
                'role' => 'Buyer',
                'name' => 'Kelly Holmes',
                'position' => 'Oral Care',
                'email' => 'kholmes@shoppersdrugmart.ca',
                'phone' => '(416) 490-2799',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 12,
                'role' => 'Buyer',
                'name' => 'Steve Mulvihill',
                'position' => 'Skin Care',
                'email' => 'Smulvihill@shoppersdrugmart.ca',
                'phone' => '(416) 490-2659',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 12,
                'role' => 'Other',
                'name' => 'Kevin Smith',
                'position' => 'Category Ass\'t-Oral Care',
                'email' => 'KeSmith@shoppersdrugmart.ca',
                'phone' => '416 493-1220 ext 5702',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 12,
                'role' => 'Other',
                'name' => 'Anna Chora',
                'position' => 'Category Ass\'t - Vitamins',
                'email' => 'achora@shoppersdrugmart.ca',
                'phone' => '(416) 493-1220 ext.5537',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 12,
                'role' => 'Other',
                'name' => 'Jonathan Lee',
                'position' => 'Category Ass\'t-NHP/C&C/Fem Care',
                'email' => 'JOlee@shoppersdrugmart.ca',
                'phone' => '(416) 493-1220 ex 5286',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 12,
                'role' => 'Other',
                'name' => 'Laurie Fleetwood',
                'position' => 'Category Ass\'t - Skin Care',
                'email' => 'LFleetwood@shoppersdrugmart.ca',
                'phone' => '(416) 493-1220 ext 5392',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 12,
                'role' => 'Other',
                'name' => 'Haroon Noori',
                'position' => 'Manager Inventory Management',
                'email' => 'Hnoori@shoppersdrugmart.ca',
                'phone' => '(416) 493-1220 ext 5639',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 12,
                'role' => 'Other',
                'name' => 'Jacqueline Stamper',
                'position' => 'Buyer',
                'email' => 'Jstamper@shoppersdrugmart.ca',
                'phone' => '(416) 493-1220 ext 3071',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 12,
                'role' => 'Other',
                'name' => 'John Georgiadis',
                'position' => 'Director Category Mgmt-OTC',
                'email' => '',
                'phone' => '(416) 493-1220',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 12,
                'role' => 'Other',
                'name' => 'Kelly Jessop',
                'position' => 'Director Category Mgmt-HBA',
                'email' => '',
                'phone' => '(416) 493-1220',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 12,
                'role' => 'Other',
                'name' => 'Sue Donaldson',
                'position' => 'Manager-Analytics',
                'email' => '',
                'phone' => '',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 13,
                'role' => 'Buyer',
                'name' => 'Lily Fernandes',
                'position' => null,
                'email' => 'lily.fernandes@shopatshowcase.com',
                'phone' => '905-452-0392 x260',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 16,
                'role' => 'Buyer',
                'name' => 'Bryan Skokandich',
                'position' => 'associate category manager Canada',
                'email' => 'bskokandich@vitaminshoppe.com',
                'phone' => '201.624.3061',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 16,
                'role' => 'Buyer',
                'name' => 'Michelle Mejia',
                'position' => 'category manager',
                'email' => 'michelle.mejia@vitaminshoppe.com',
                'phone' => '201.624.3283',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 17,
                'role' => 'Buyer',
                'name' => 'Brad Eltherington',
                'position' => 'D40 Vitamins / Teas',
                'email' => 'brad.eltherington@wal-mart.com',
                'phone' => '905-821-2111 x',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 17,
                'role' => 'Buyer',
                'name' => 'Grant Hennig',
                'position' => 'D40 Natural HBA',
                'email' => 'grant.hennig@wal-mart.com',
                'phone' => '905-821-2111 ext 4005',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 17,
                'role' => 'Buyer',
                'name' => 'Caroline Pius',
                'position' => 'D46 Specialty Bath',
                'email' => 'Caroline.Pius@wal-mart.com',
                'phone' => '(905) 821-2111 x4417',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 17,
                'role' => 'Buyer',
                'name' => 'Julius Fernandes',
                'position' => 'Body / Fem. Hygiene / Oral Care',
                'email' => 'julius.fernandes@wal-mart.com',
                'phone' => '905-821-2111 x',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 17,
                'role' => 'Buyer',
                'name' => 'Diane Wallace',
                'position' => 'Hair Care',
                'email' => 'dwallac@wal-mart.com',
                'phone' => '905-821-2111 x',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 17,
                'role' => 'Buyer',
                'name' => 'Tanya Spencer',
                'position' => 'Skin Care',
                'email' => 'tanya.spencer@wal-mart.com',
                'phone' => '905-821-2111 x',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 17,
                'role' => 'Other',
                'name' => 'Mark Hilton',
                'position' => 'DMM',
                'email' => 'Mark.Hilton@wal-mart.com',
                'phone' => '905-821-2111 ext 8396',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 17,
                'role' => 'Other',
                'name' => 'Nazeema Mohabir',
                'position' => 'Pharmacy Merchandise Assistant',
                'email' => 'Nazeema.Mohabir@wal-mart.com',
                'phone' => '905-821-2111 ext 8394',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 17,
                'role' => 'Other',
                'name' => 'Jessica Pacheco',
                'position' => 'Category Team Analyst',
                'email' => 'Jessica.Pacheco@wal-mart.com',
                'phone' => '(905) 821-2111 ext. 4047',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 19,
                'role' => 'Buyer',
                'name' => 'Rob Luscombe',
                'position' => 'Grocery Buyer',
                'email' => 'Rob.Luscombe@wholefoods.com',
                'phone' => '(905) 273-0192',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 19,
                'role' => 'Buyer',
                'name' => 'Drew Mara-McKay',
                'position' => 'Whole Body Buyer',
                'email' => 'andrew.mara-mckay@wholefoods.com',
                'phone' => '(905) 273-0193',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 19,
                'role' => 'Other',
                'name' => 'Gary MacDonald',
                'position' => 'Purchasing Coordinator',
                'email' => 'gary.macdonald@wholefoods.com',
                'phone' => '905.273.0191',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 19,
                'role' => 'Other',
                'name' => ' ',
                'position' => 'Category Review Submissions',
                'email' => 'MW.ONT.GRO.WB.CATEGORY.REVIEW@wholefoods.com',
                'phone' => '',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 19,
                'role' => 'Other',
                'name' => 'Beth Eckerty',
                'position' => 'MW Whole Body Coordinator',
                'email' => 'Beth.Eckerty@wholefoods.com',
                'phone' => '312.799.5623',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 20,
                'role' => 'Buyer',
                'name' => 'Mary Frewen',
                'position' => 'Whole Body',
                'email' => 'mary.frewen@wholefoods.com',
                'phone' => '236-521-2707',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 20,
                'role' => 'Buyer',
                'name' => 'Richard Williams',
                'position' => 'Grocery',
                'email' => 'Richard.Williams@wholefoods.com',
                'phone' => '236-521-2706',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 20,
                'role' => 'Other',
                'name' => 'Suzanne Geohagan',
                'position' => 'Whole Body Coordinator',
                'email' => 'Suzanne.Geohagan@wholefoods.com',
                'phone' => '',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 20,
                'role' => 'Other',
                'name' => 'Elaine Arrowsmith',
                'position' => 'Pacific Northwest region',
                'email' => 'Elaine.Arrowsmith@wholefoods.com',
                'phone' => '236.521.2705',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
            [
                'contactable_type' => 'App\\Models\\Retailer',
                'contactable_id' => 20,
                'role' => 'Other',
                'name' => 'Bruce Cancilla',
                'position' => 'Purchasing Coordinator Western Canada',
                'email' => 'Bruce.Cancilla@wholefoods.com',
                'phone' => '',
                'created_at' => '2020-08-19 11:30:38',
                'updated_at' => '2020-08-19 11:30:38',
            ],
        ];
        DB::table('contacts')->insert($retailerContacts);

        // Retailer Distributors
        DB::table('distributor_retailer')->insert([
            0 => [
                'distributor_id' => 3,
                'retailer_id' => 12,
            ],
            1 => [
                'distributor_id' => 2,
                'retailer_id' => 15,
            ],
            2 => [
                'distributor_id' => 1,
                'retailer_id' => 17,
            ],
        ]);
    }
}
