<?php

namespace Database\Seeders\Development\iseed;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class As400PricingTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('as400_pricing')->delete();

        DB::table('as400_pricing')->insert([

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 1,
                'average_landed_cost' => '13.01',
                'next_po_price' => null,
                'po_price' => '9.43',
                'po_price_expiry' => null,
                'product_id' => 200,
                'taxable' => 1,
                'wholesale_price' => '17.46',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 2,
                'average_landed_cost' => '7.10',
                'next_po_price' => null,
                'po_price' => '7.10',
                'po_price_expiry' => null,
                'product_id' => 199,
                'taxable' => 1,
                'wholesale_price' => '9.59',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 3,
                'average_landed_cost' => '3.33',
                'next_po_price' => null,
                'po_price' => '3.33',
                'po_price_expiry' => null,
                'product_id' => 198,
                'taxable' => 1,
                'wholesale_price' => '4.50',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 4,
                'average_landed_cost' => '3.70',
                'next_po_price' => null,
                'po_price' => '3.70',
                'po_price_expiry' => null,
                'product_id' => 197,
                'taxable' => 1,
                'wholesale_price' => '5.00',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 5,
                'average_landed_cost' => '3.70',
                'next_po_price' => null,
                'po_price' => '3.70',
                'po_price_expiry' => null,
                'product_id' => 196,
                'taxable' => 1,
                'wholesale_price' => '5.00',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 6,
                'average_landed_cost' => '2.59',
                'next_po_price' => null,
                'po_price' => '2.59',
                'po_price_expiry' => null,
                'product_id' => 195,
                'taxable' => 1,
                'wholesale_price' => '3.50',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 7,
                'average_landed_cost' => '2.59',
                'next_po_price' => null,
                'po_price' => '2.59',
                'po_price_expiry' => null,
                'product_id' => 194,
                'taxable' => 1,
                'wholesale_price' => '3.50',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 8,
                'average_landed_cost' => '2.59',
                'next_po_price' => null,
                'po_price' => '2.59',
                'po_price_expiry' => null,
                'product_id' => 193,
                'taxable' => 1,
                'wholesale_price' => '3.50',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 9,
                'average_landed_cost' => '2.59',
                'next_po_price' => null,
                'po_price' => '2.59',
                'po_price_expiry' => null,
                'product_id' => 192,
                'taxable' => 1,
                'wholesale_price' => '3.50',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 10,
                'average_landed_cost' => '9.62',
                'next_po_price' => null,
                'po_price' => '9.62',
                'po_price_expiry' => null,
                'product_id' => 191,
                'taxable' => 1,
                'wholesale_price' => '13.00',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 11,
                'average_landed_cost' => '14.43',
                'next_po_price' => null,
                'po_price' => '14.43',
                'po_price_expiry' => null,
                'product_id' => 190,
                'taxable' => 1,
                'wholesale_price' => '19.50',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 12,
                'average_landed_cost' => '9.62',
                'next_po_price' => null,
                'po_price' => '9.62',
                'po_price_expiry' => null,
                'product_id' => 189,
                'taxable' => 1,
                'wholesale_price' => '13.00',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 13,
                'average_landed_cost' => '2.59',
                'next_po_price' => null,
                'po_price' => '2.59',
                'po_price_expiry' => null,
                'product_id' => 188,
                'taxable' => 1,
                'wholesale_price' => '3.50',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 14,
                'average_landed_cost' => '2.59',
                'next_po_price' => null,
                'po_price' => '2.59',
                'po_price_expiry' => null,
                'product_id' => 187,
                'taxable' => 1,
                'wholesale_price' => '3.50',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 15,
                'average_landed_cost' => '2.59',
                'next_po_price' => null,
                'po_price' => '2.59',
                'po_price_expiry' => null,
                'product_id' => 186,
                'taxable' => 1,
                'wholesale_price' => '3.50',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 16,
                'average_landed_cost' => '2.59',
                'next_po_price' => null,
                'po_price' => '2.59',
                'po_price_expiry' => null,
                'product_id' => 185,
                'taxable' => 1,
                'wholesale_price' => '3.50',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 17,
                'average_landed_cost' => '2.59',
                'next_po_price' => null,
                'po_price' => '2.59',
                'po_price_expiry' => null,
                'product_id' => 184,
                'taxable' => 1,
                'wholesale_price' => '3.50',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 18,
                'average_landed_cost' => '3.10',
                'next_po_price' => null,
                'po_price' => '3.10',
                'po_price_expiry' => null,
                'product_id' => 183,
                'taxable' => 1,
                'wholesale_price' => '4.19',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 19,
                'average_landed_cost' => '3.10',
                'next_po_price' => null,
                'po_price' => '3.10',
                'po_price_expiry' => null,
                'product_id' => 182,
                'taxable' => 1,
                'wholesale_price' => '4.19',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 20,
                'average_landed_cost' => '3.10',
                'next_po_price' => null,
                'po_price' => '3.10',
                'po_price_expiry' => null,
                'product_id' => 181,
                'taxable' => 1,
                'wholesale_price' => '4.19',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 21,
                'average_landed_cost' => '3.10',
                'next_po_price' => null,
                'po_price' => '3.10',
                'po_price_expiry' => null,
                'product_id' => 180,
                'taxable' => 1,
                'wholesale_price' => '4.19',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 22,
                'average_landed_cost' => '3.10',
                'next_po_price' => null,
                'po_price' => '3.10',
                'po_price_expiry' => null,
                'product_id' => 179,
                'taxable' => 1,
                'wholesale_price' => '4.19',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 23,
                'average_landed_cost' => '773.88',
                'next_po_price' => null,
                'po_price' => '773.88',
                'po_price_expiry' => null,
                'product_id' => 178,
                'taxable' => 1,
                'wholesale_price' => '1045.80',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 24,
                'average_landed_cost' => '840.24',
                'next_po_price' => null,
                'po_price' => '840.24',
                'po_price_expiry' => null,
                'product_id' => 177,
                'taxable' => 1,
                'wholesale_price' => '1135.50',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 25,
                'average_landed_cost' => '840.24',
                'next_po_price' => null,
                'po_price' => '840.24',
                'po_price_expiry' => null,
                'product_id' => 176,
                'taxable' => 1,
                'wholesale_price' => '1135.50',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 26,
                'average_landed_cost' => '7.48',
                'next_po_price' => null,
                'po_price' => '4.95',
                'po_price_expiry' => null,
                'product_id' => 175,
                'taxable' => 1,
                'wholesale_price' => '9.62',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 27,
                'average_landed_cost' => '7.30',
                'next_po_price' => null,
                'po_price' => '4.95',
                'po_price_expiry' => null,
                'product_id' => 174,
                'taxable' => 1,
                'wholesale_price' => '9.62',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 28,
                'average_landed_cost' => '7.48',
                'next_po_price' => null,
                'po_price' => '4.95',
                'po_price_expiry' => null,
                'product_id' => 173,
                'taxable' => 1,
                'wholesale_price' => '9.62',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 29,
                'average_landed_cost' => '117.56',
                'next_po_price' => null,
                'po_price' => '111.96',
                'po_price_expiry' => null,
                'product_id' => 172,
                'taxable' => 1,
                'wholesale_price' => '158.86',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 30,
                'average_landed_cost' => '55.69',
                'next_po_price' => null,
                'po_price' => '53.04',
                'po_price_expiry' => null,
                'product_id' => 171,
                'taxable' => 1,
                'wholesale_price' => '75.26',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 31,
                'average_landed_cost' => '17.64',
                'next_po_price' => null,
                'po_price' => '16.80',
                'po_price_expiry' => null,
                'product_id' => 170,
                'taxable' => 0,
                'wholesale_price' => '23.84',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 32,
                'average_landed_cost' => '17.64',
                'next_po_price' => null,
                'po_price' => '16.80',
                'po_price_expiry' => null,
                'product_id' => 169,
                'taxable' => 0,
                'wholesale_price' => '23.84',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 33,
                'average_landed_cost' => '17.64',
                'next_po_price' => null,
                'po_price' => '16.80',
                'po_price_expiry' => null,
                'product_id' => 168,
                'taxable' => 0,
                'wholesale_price' => '23.84',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 34,
                'average_landed_cost' => '17.64',
                'next_po_price' => null,
                'po_price' => '16.80',
                'po_price_expiry' => null,
                'product_id' => 167,
                'taxable' => 0,
                'wholesale_price' => '23.84',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 35,
                'average_landed_cost' => '105.84',
                'next_po_price' => null,
                'po_price' => '100.80',
                'po_price_expiry' => null,
                'product_id' => 166,
                'taxable' => 0,
                'wholesale_price' => '143.03',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 36,
                'average_landed_cost' => '6.96',
                'next_po_price' => null,
                'po_price' => '7.28',
                'po_price_expiry' => null,
                'product_id' => 165,
                'taxable' => 1,
                'wholesale_price' => '9.10',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 37,
                'average_landed_cost' => '22.19',
                'next_po_price' => null,
                'po_price' => '22.19',
                'po_price_expiry' => null,
                'product_id' => 164,
                'taxable' => 1,
                'wholesale_price' => '29.99',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 38,
                'average_landed_cost' => '22.19',
                'next_po_price' => null,
                'po_price' => '22.19',
                'po_price_expiry' => null,
                'product_id' => 163,
                'taxable' => 1,
                'wholesale_price' => '29.99',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 39,
                'average_landed_cost' => '33.29',
                'next_po_price' => null,
                'po_price' => '33.29',
                'po_price_expiry' => null,
                'product_id' => 162,
                'taxable' => 1,
                'wholesale_price' => '44.99',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 40,
                'average_landed_cost' => '33.29',
                'next_po_price' => null,
                'po_price' => '33.29',
                'po_price_expiry' => null,
                'product_id' => 161,
                'taxable' => 1,
                'wholesale_price' => '44.99',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 41,
                'average_landed_cost' => '4.34',
                'next_po_price' => null,
                'po_price' => '4.23',
                'po_price_expiry' => null,
                'product_id' => 160,
                'taxable' => 0,
                'wholesale_price' => '5.39',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 42,
                'average_landed_cost' => '4.33',
                'next_po_price' => null,
                'po_price' => '4.23',
                'po_price_expiry' => null,
                'product_id' => 159,
                'taxable' => 0,
                'wholesale_price' => '5.39',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 43,
                'average_landed_cost' => '9.98',
                'next_po_price' => null,
                'po_price' => '9.98',
                'po_price_expiry' => null,
                'product_id' => 158,
                'taxable' => 1,
                'wholesale_price' => '13.49',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 44,
                'average_landed_cost' => '9.98',
                'next_po_price' => null,
                'po_price' => '9.98',
                'po_price_expiry' => null,
                'product_id' => 157,
                'taxable' => 1,
                'wholesale_price' => '13.49',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 45,
                'average_landed_cost' => '9.98',
                'next_po_price' => null,
                'po_price' => '9.98',
                'po_price_expiry' => null,
                'product_id' => 156,
                'taxable' => 1,
                'wholesale_price' => '13.49',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 46,
                'average_landed_cost' => '13.76',
                'next_po_price' => null,
                'po_price' => '13.76',
                'po_price_expiry' => null,
                'product_id' => 155,
                'taxable' => 1,
                'wholesale_price' => '18.59',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 47,
                'average_landed_cost' => '10.54',
                'next_po_price' => null,
                'po_price' => '10.54',
                'po_price_expiry' => null,
                'product_id' => 154,
                'taxable' => 1,
                'wholesale_price' => '14.24',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 48,
                'average_landed_cost' => '16.29',
                'next_po_price' => null,
                'po_price' => '15.52',
                'po_price_expiry' => null,
                'product_id' => 153,
                'taxable' => 1,
                'wholesale_price' => '22.02',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 49,
                'average_landed_cost' => '16.30',
                'next_po_price' => null,
                'po_price' => '15.52',
                'po_price_expiry' => null,
                'product_id' => 152,
                'taxable' => 1,
                'wholesale_price' => '22.02',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 50,
                'average_landed_cost' => '48.76',
                'next_po_price' => null,
                'po_price' => '46.44',
                'po_price_expiry' => null,
                'product_id' => 151,
                'taxable' => 1,
                'wholesale_price' => '65.90',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 51,
                'average_landed_cost' => '6.35',
                'next_po_price' => null,
                'po_price' => '6.35',
                'po_price_expiry' => null,
                'product_id' => 150,
                'taxable' => 1,
                'wholesale_price' => '10.08',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 52,
                'average_landed_cost' => '5.86',
                'next_po_price' => null,
                'po_price' => '4.26',
                'po_price_expiry' => null,
                'product_id' => 149,
                'taxable' => 1,
                'wholesale_price' => '7.89',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 53,
                'average_landed_cost' => '5.89',
                'next_po_price' => null,
                'po_price' => '4.26',
                'po_price_expiry' => null,
                'product_id' => 148,
                'taxable' => 1,
                'wholesale_price' => '7.89',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 54,
                'average_landed_cost' => '5.89',
                'next_po_price' => null,
                'po_price' => '4.26',
                'po_price_expiry' => null,
                'product_id' => 147,
                'taxable' => 1,
                'wholesale_price' => '7.89',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 55,
                'average_landed_cost' => '5.86',
                'next_po_price' => null,
                'po_price' => '4.26',
                'po_price_expiry' => null,
                'product_id' => 146,
                'taxable' => 1,
                'wholesale_price' => '7.89',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 56,
                'average_landed_cost' => '6.10',
                'next_po_price' => null,
                'po_price' => '4.26',
                'po_price_expiry' => null,
                'product_id' => 145,
                'taxable' => 1,
                'wholesale_price' => '7.89',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 57,
                'average_landed_cost' => '5.98',
                'next_po_price' => null,
                'po_price' => '4.26',
                'po_price_expiry' => null,
                'product_id' => 144,
                'taxable' => 1,
                'wholesale_price' => '7.89',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 58,
                'average_landed_cost' => '5.96',
                'next_po_price' => null,
                'po_price' => '4.26',
                'po_price_expiry' => null,
                'product_id' => 143,
                'taxable' => 1,
                'wholesale_price' => '7.89',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 59,
                'average_landed_cost' => '534.23',
                'next_po_price' => null,
                'po_price' => '371.38',
                'po_price_expiry' => null,
                'product_id' => 142,
                'taxable' => 1,
                'wholesale_price' => '721.93',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 60,
                'average_landed_cost' => '31.52',
                'next_po_price' => null,
                'po_price' => '31.52',
                'po_price_expiry' => null,
                'product_id' => 141,
                'taxable' => 1,
                'wholesale_price' => '42.59',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 61,
                'average_landed_cost' => '26.19',
                'next_po_price' => null,
                'po_price' => '36.19',
                'po_price_expiry' => null,
                'product_id' => 140,
                'taxable' => 1,
                'wholesale_price' => '48.91',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 62,
                'average_landed_cost' => '5.89',
                'next_po_price' => null,
                'po_price' => '4.26',
                'po_price_expiry' => null,
                'product_id' => 139,
                'taxable' => 1,
                'wholesale_price' => '7.89',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 63,
                'average_landed_cost' => '11.70',
                'next_po_price' => null,
                'po_price' => '8.54',
                'po_price_expiry' => null,
                'product_id' => 138,
                'taxable' => 1,
                'wholesale_price' => '15.81',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 64,
                'average_landed_cost' => '44.67',
                'next_po_price' => null,
                'po_price' => '32.31',
                'po_price_expiry' => null,
                'product_id' => 137,
                'taxable' => 1,
                'wholesale_price' => '59.81',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 65,
                'average_landed_cost' => '37.16',
                'next_po_price' => null,
                'po_price' => '26.91',
                'po_price_expiry' => null,
                'product_id' => 136,
                'taxable' => 1,
                'wholesale_price' => '49.82',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 66,
                'average_landed_cost' => '46.10',
                'next_po_price' => null,
                'po_price' => '32.31',
                'po_price_expiry' => null,
                'product_id' => 135,
                'taxable' => 1,
                'wholesale_price' => '59.81',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 67,
                'average_landed_cost' => '37.26',
                'next_po_price' => null,
                'po_price' => '26.91',
                'po_price_expiry' => null,
                'product_id' => 134,
                'taxable' => 1,
                'wholesale_price' => '49.82',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 68,
                'average_landed_cost' => '37.49',
                'next_po_price' => null,
                'po_price' => '26.91',
                'po_price_expiry' => null,
                'product_id' => 133,
                'taxable' => 1,
                'wholesale_price' => '49.82',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 69,
                'average_landed_cost' => '37.19',
                'next_po_price' => null,
                'po_price' => '26.91',
                'po_price_expiry' => null,
                'product_id' => 132,
                'taxable' => 1,
                'wholesale_price' => '49.82',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 70,
                'average_landed_cost' => '37.56',
                'next_po_price' => null,
                'po_price' => '26.91',
                'po_price_expiry' => null,
                'product_id' => 131,
                'taxable' => 1,
                'wholesale_price' => '49.82',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 71,
                'average_landed_cost' => '37.27',
                'next_po_price' => null,
                'po_price' => '26.91',
                'po_price_expiry' => null,
                'product_id' => 130,
                'taxable' => 1,
                'wholesale_price' => '49.82',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 72,
                'average_landed_cost' => '12.32',
                'next_po_price' => null,
                'po_price' => '8.99',
                'po_price_expiry' => null,
                'product_id' => 129,
                'taxable' => 1,
                'wholesale_price' => '16.65',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 73,
                'average_landed_cost' => '12.16',
                'next_po_price' => null,
                'po_price' => '8.54',
                'po_price_expiry' => null,
                'product_id' => 128,
                'taxable' => 1,
                'wholesale_price' => '15.81',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 74,
                'average_landed_cost' => '8.00',
                'next_po_price' => null,
                'po_price' => '5.84',
                'po_price_expiry' => null,
                'product_id' => 127,
                'taxable' => 1,
                'wholesale_price' => '10.81',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 75,
                'average_landed_cost' => '8.00',
                'next_po_price' => null,
                'po_price' => '5.84',
                'po_price_expiry' => null,
                'product_id' => 126,
                'taxable' => 1,
                'wholesale_price' => '10.81',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 76,
                'average_landed_cost' => '7.51',
                'next_po_price' => null,
                'po_price' => '5.39',
                'po_price_expiry' => null,
                'product_id' => 125,
                'taxable' => 1,
                'wholesale_price' => '9.97',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 77,
                'average_landed_cost' => '7.40',
                'next_po_price' => null,
                'po_price' => '5.39',
                'po_price_expiry' => null,
                'product_id' => 124,
                'taxable' => 1,
                'wholesale_price' => '9.97',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 78,
                'average_landed_cost' => '5.54',
                'next_po_price' => null,
                'po_price' => '4.04',
                'po_price_expiry' => null,
                'product_id' => 123,
                'taxable' => 1,
                'wholesale_price' => '7.47',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 79,
                'average_landed_cost' => '5.59',
                'next_po_price' => null,
                'po_price' => '4.04',
                'po_price_expiry' => null,
                'product_id' => 122,
                'taxable' => 1,
                'wholesale_price' => '7.47',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 80,
                'average_landed_cost' => '5.57',
                'next_po_price' => null,
                'po_price' => '4.04',
                'po_price_expiry' => null,
                'product_id' => 121,
                'taxable' => 1,
                'wholesale_price' => '7.47',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 81,
                'average_landed_cost' => '5.63',
                'next_po_price' => null,
                'po_price' => '4.04',
                'po_price_expiry' => null,
                'product_id' => 120,
                'taxable' => 1,
                'wholesale_price' => '7.47',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 82,
                'average_landed_cost' => '184.80',
                'next_po_price' => null,
                'po_price' => '176.00',
                'po_price_expiry' => null,
                'product_id' => 119,
                'taxable' => 0,
                'wholesale_price' => '249.73',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 83,
                'average_landed_cost' => '18.00',
                'next_po_price' => null,
                'po_price' => '18.00',
                'po_price_expiry' => null,
                'product_id' => 118,
                'taxable' => 1,
                'wholesale_price' => '24.00',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 84,
                'average_landed_cost' => '18.00',
                'next_po_price' => null,
                'po_price' => '18.00',
                'po_price_expiry' => null,
                'product_id' => 117,
                'taxable' => 1,
                'wholesale_price' => '24.00',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 85,
                'average_landed_cost' => '18.00',
                'next_po_price' => null,
                'po_price' => '18.00',
                'po_price_expiry' => null,
                'product_id' => 116,
                'taxable' => 1,
                'wholesale_price' => '24.00',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 86,
                'average_landed_cost' => '7.21',
                'next_po_price' => null,
                'po_price' => '7.21',
                'po_price_expiry' => null,
                'product_id' => 115,
                'taxable' => 1,
                'wholesale_price' => '9.74',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 87,
                'average_landed_cost' => '7.21',
                'next_po_price' => null,
                'po_price' => '7.21',
                'po_price_expiry' => null,
                'product_id' => 114,
                'taxable' => 1,
                'wholesale_price' => '9.74',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 88,
                'average_landed_cost' => '7.21',
                'next_po_price' => null,
                'po_price' => '7.21',
                'po_price_expiry' => null,
                'product_id' => 113,
                'taxable' => 1,
                'wholesale_price' => '9.74',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 89,
                'average_landed_cost' => '7.21',
                'next_po_price' => null,
                'po_price' => '7.21',
                'po_price_expiry' => null,
                'product_id' => 112,
                'taxable' => 1,
                'wholesale_price' => '9.74',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 90,
                'average_landed_cost' => '7.21',
                'next_po_price' => null,
                'po_price' => '7.21',
                'po_price_expiry' => null,
                'product_id' => 111,
                'taxable' => 1,
                'wholesale_price' => '9.74',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 91,
                'average_landed_cost' => '7.21',
                'next_po_price' => null,
                'po_price' => '7.21',
                'po_price_expiry' => null,
                'product_id' => 110,
                'taxable' => 1,
                'wholesale_price' => '9.74',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 92,
                'average_landed_cost' => '7.21',
                'next_po_price' => null,
                'po_price' => '7.21',
                'po_price_expiry' => null,
                'product_id' => 109,
                'taxable' => 1,
                'wholesale_price' => '9.74',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 93,
                'average_landed_cost' => '7.21',
                'next_po_price' => null,
                'po_price' => '7.21',
                'po_price_expiry' => null,
                'product_id' => 108,
                'taxable' => 1,
                'wholesale_price' => '9.74',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 94,
                'average_landed_cost' => '16.87',
                'next_po_price' => null,
                'po_price' => '16.87',
                'po_price_expiry' => null,
                'product_id' => 107,
                'taxable' => 1,
                'wholesale_price' => '22.49',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 95,
                'average_landed_cost' => '4.00',
                'next_po_price' => null,
                'po_price' => '4.00',
                'po_price_expiry' => null,
                'product_id' => 106,
                'taxable' => 1,
                'wholesale_price' => '5.41',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 96,
                'average_landed_cost' => '4.00',
                'next_po_price' => null,
                'po_price' => '4.00',
                'po_price_expiry' => null,
                'product_id' => 105,
                'taxable' => 1,
                'wholesale_price' => '5.41',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 97,
                'average_landed_cost' => '4.00',
                'next_po_price' => null,
                'po_price' => '4.00',
                'po_price_expiry' => null,
                'product_id' => 104,
                'taxable' => 1,
                'wholesale_price' => '5.41',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 98,
                'average_landed_cost' => '4.00',
                'next_po_price' => null,
                'po_price' => '4.00',
                'po_price_expiry' => null,
                'product_id' => 103,
                'taxable' => 1,
                'wholesale_price' => '5.41',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 99,
                'average_landed_cost' => '7.22',
                'next_po_price' => null,
                'po_price' => '7.21',
                'po_price_expiry' => null,
                'product_id' => 102,
                'taxable' => 1,
                'wholesale_price' => '9.74',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 100,
                'average_landed_cost' => '7.21',
                'next_po_price' => null,
                'po_price' => '7.21',
                'po_price_expiry' => null,
                'product_id' => 101,
                'taxable' => 1,
                'wholesale_price' => '9.74',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 101,
                'average_landed_cost' => '7.21',
                'next_po_price' => null,
                'po_price' => '7.21',
                'po_price_expiry' => null,
                'product_id' => 100,
                'taxable' => 1,
                'wholesale_price' => '9.74',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 102,
                'average_landed_cost' => '7.21',
                'next_po_price' => null,
                'po_price' => '7.21',
                'po_price_expiry' => null,
                'product_id' => 99,
                'taxable' => 1,
                'wholesale_price' => '9.74',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 103,
                'average_landed_cost' => '7.21',
                'next_po_price' => null,
                'po_price' => '7.21',
                'po_price_expiry' => null,
                'product_id' => 98,
                'taxable' => 1,
                'wholesale_price' => '9.74',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 104,
                'average_landed_cost' => '13.76',
                'next_po_price' => null,
                'po_price' => '13.76',
                'po_price_expiry' => null,
                'product_id' => 97,
                'taxable' => 1,
                'wholesale_price' => '18.59',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 105,
                'average_landed_cost' => '13.76',
                'next_po_price' => null,
                'po_price' => '13.76',
                'po_price_expiry' => null,
                'product_id' => 96,
                'taxable' => 1,
                'wholesale_price' => '18.59',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 106,
                'average_landed_cost' => '13.76',
                'next_po_price' => null,
                'po_price' => '13.76',
                'po_price_expiry' => null,
                'product_id' => 95,
                'taxable' => 1,
                'wholesale_price' => '18.59',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 107,
                'average_landed_cost' => '6.63',
                'next_po_price' => null,
                'po_price' => '6.63',
                'po_price_expiry' => null,
                'product_id' => 94,
                'taxable' => 1,
                'wholesale_price' => '8.96',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 108,
                'average_landed_cost' => '6.63',
                'next_po_price' => null,
                'po_price' => '6.63',
                'po_price_expiry' => null,
                'product_id' => 93,
                'taxable' => 1,
                'wholesale_price' => '8.96',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 109,
                'average_landed_cost' => '6.63',
                'next_po_price' => null,
                'po_price' => '6.63',
                'po_price_expiry' => null,
                'product_id' => 92,
                'taxable' => 1,
                'wholesale_price' => '8.96',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 110,
                'average_landed_cost' => '10.54',
                'next_po_price' => null,
                'po_price' => '10.54',
                'po_price_expiry' => null,
                'product_id' => 91,
                'taxable' => 1,
                'wholesale_price' => '14.24',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 111,
                'average_landed_cost' => '10.54',
                'next_po_price' => null,
                'po_price' => '10.54',
                'po_price_expiry' => null,
                'product_id' => 90,
                'taxable' => 1,
                'wholesale_price' => '14.24',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 112,
                'average_landed_cost' => '10.54',
                'next_po_price' => null,
                'po_price' => '10.54',
                'po_price_expiry' => null,
                'product_id' => 89,
                'taxable' => 1,
                'wholesale_price' => '14.24',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 113,
                'average_landed_cost' => '11.10',
                'next_po_price' => null,
                'po_price' => '11.10',
                'po_price_expiry' => null,
                'product_id' => 88,
                'taxable' => 1,
                'wholesale_price' => '15.00',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 114,
                'average_landed_cost' => '11.10',
                'next_po_price' => null,
                'po_price' => '11.10',
                'po_price_expiry' => null,
                'product_id' => 87,
                'taxable' => 1,
                'wholesale_price' => '15.00',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 115,
                'average_landed_cost' => '11.10',
                'next_po_price' => null,
                'po_price' => '11.10',
                'po_price_expiry' => null,
                'product_id' => 86,
                'taxable' => 1,
                'wholesale_price' => '15.00',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 116,
                'average_landed_cost' => '16.65',
                'next_po_price' => null,
                'po_price' => '16.65',
                'po_price_expiry' => null,
                'product_id' => 85,
                'taxable' => 1,
                'wholesale_price' => '22.50',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 117,
                'average_landed_cost' => '16.65',
                'next_po_price' => null,
                'po_price' => '16.65',
                'po_price_expiry' => null,
                'product_id' => 84,
                'taxable' => 1,
                'wholesale_price' => '22.50',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 118,
                'average_landed_cost' => '16.65',
                'next_po_price' => null,
                'po_price' => '16.65',
                'po_price_expiry' => null,
                'product_id' => 83,
                'taxable' => 1,
                'wholesale_price' => '22.50',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 119,
                'average_landed_cost' => '15.64',
                'next_po_price' => null,
                'po_price' => '16.65',
                'po_price_expiry' => null,
                'product_id' => 82,
                'taxable' => 1,
                'wholesale_price' => '22.50',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 120,
                'average_landed_cost' => '12.69',
                'next_po_price' => null,
                'po_price' => '16.65',
                'po_price_expiry' => null,
                'product_id' => 81,
                'taxable' => 1,
                'wholesale_price' => '22.50',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 121,
                'average_landed_cost' => '6.63',
                'next_po_price' => null,
                'po_price' => '6.63',
                'po_price_expiry' => null,
                'product_id' => 80,
                'taxable' => 1,
                'wholesale_price' => '8.96',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 122,
                'average_landed_cost' => '6.63',
                'next_po_price' => null,
                'po_price' => '6.63',
                'po_price_expiry' => null,
                'product_id' => 79,
                'taxable' => 1,
                'wholesale_price' => '8.96',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 123,
                'average_landed_cost' => '11.07',
                'next_po_price' => null,
                'po_price' => '11.07',
                'po_price_expiry' => null,
                'product_id' => 78,
                'taxable' => 1,
                'wholesale_price' => '14.96',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 124,
                'average_landed_cost' => '11.07',
                'next_po_price' => null,
                'po_price' => '11.07',
                'po_price_expiry' => null,
                'product_id' => 77,
                'taxable' => 1,
                'wholesale_price' => '14.96',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 125,
                'average_landed_cost' => '18.00',
                'next_po_price' => null,
                'po_price' => '18.00',
                'po_price_expiry' => null,
                'product_id' => 76,
                'taxable' => 1,
                'wholesale_price' => '24.00',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 126,
                'average_landed_cost' => '18.00',
                'next_po_price' => null,
                'po_price' => '18.00',
                'po_price_expiry' => null,
                'product_id' => 75,
                'taxable' => 1,
                'wholesale_price' => '24.00',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 127,
                'average_landed_cost' => '18.00',
                'next_po_price' => null,
                'po_price' => '18.00',
                'po_price_expiry' => null,
                'product_id' => 74,
                'taxable' => 1,
                'wholesale_price' => '24.00',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 128,
                'average_landed_cost' => '20.40',
                'next_po_price' => null,
                'po_price' => '22.20',
                'po_price_expiry' => null,
                'product_id' => 73,
                'taxable' => 1,
                'wholesale_price' => '27.20',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 129,
                'average_landed_cost' => '12.91',
                'next_po_price' => null,
                'po_price' => '13.35',
                'po_price_expiry' => null,
                'product_id' => 72,
                'taxable' => 1,
                'wholesale_price' => '16.69',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 130,
                'average_landed_cost' => '6.19',
                'next_po_price' => null,
                'po_price' => '4.49',
                'po_price_expiry' => null,
                'product_id' => 71,
                'taxable' => 1,
                'wholesale_price' => '8.31',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 131,
                'average_landed_cost' => '6.17',
                'next_po_price' => null,
                'po_price' => '4.49',
                'po_price_expiry' => null,
                'product_id' => 70,
                'taxable' => 1,
                'wholesale_price' => '8.31',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 132,
                'average_landed_cost' => '6.25',
                'next_po_price' => null,
                'po_price' => '4.49',
                'po_price_expiry' => null,
                'product_id' => 69,
                'taxable' => 1,
                'wholesale_price' => '8.31',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 133,
                'average_landed_cost' => '6.18',
                'next_po_price' => null,
                'po_price' => '4.49',
                'po_price_expiry' => null,
                'product_id' => 68,
                'taxable' => 1,
                'wholesale_price' => '8.31',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 134,
                'average_landed_cost' => '6.29',
                'next_po_price' => null,
                'po_price' => '4.49',
                'po_price_expiry' => null,
                'product_id' => 67,
                'taxable' => 1,
                'wholesale_price' => '8.31',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 135,
                'average_landed_cost' => '6.19',
                'next_po_price' => null,
                'po_price' => '4.49',
                'po_price_expiry' => null,
                'product_id' => 66,
                'taxable' => 1,
                'wholesale_price' => '8.31',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 136,
                'average_landed_cost' => '6.16',
                'next_po_price' => null,
                'po_price' => '4.49',
                'po_price_expiry' => null,
                'product_id' => 65,
                'taxable' => 1,
                'wholesale_price' => '8.31',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 137,
                'average_landed_cost' => '6.17',
                'next_po_price' => null,
                'po_price' => '4.49',
                'po_price_expiry' => null,
                'product_id' => 64,
                'taxable' => 1,
                'wholesale_price' => '8.31',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 138,
                'average_landed_cost' => '52.40',
                'next_po_price' => null,
                'po_price' => '37.71',
                'po_price_expiry' => null,
                'product_id' => 63,
                'taxable' => 1,
                'wholesale_price' => '69.81',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 139,
                'average_landed_cost' => '52.04',
                'next_po_price' => null,
                'po_price' => '37.71',
                'po_price_expiry' => null,
                'product_id' => 62,
                'taxable' => 1,
                'wholesale_price' => '69.81',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 140,
                'average_landed_cost' => '6.63',
                'next_po_price' => null,
                'po_price' => '6.63',
                'po_price_expiry' => null,
                'product_id' => 61,
                'taxable' => 1,
                'wholesale_price' => '8.96',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 141,
                'average_landed_cost' => '11.56',
                'next_po_price' => null,
                'po_price' => '8.11',
                'po_price_expiry' => null,
                'product_id' => 60,
                'taxable' => 1,
                'wholesale_price' => '15.01',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 142,
                'average_landed_cost' => '11.45',
                'next_po_price' => null,
                'po_price' => '8.11',
                'po_price_expiry' => null,
                'product_id' => 59,
                'taxable' => 1,
                'wholesale_price' => '15.01',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 143,
                'average_landed_cost' => '11.35',
                'next_po_price' => null,
                'po_price' => '8.11',
                'po_price_expiry' => null,
                'product_id' => 58,
                'taxable' => 1,
                'wholesale_price' => '15.01',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 144,
                'average_landed_cost' => '11.48',
                'next_po_price' => null,
                'po_price' => '8.11',
                'po_price_expiry' => null,
                'product_id' => 57,
                'taxable' => 1,
                'wholesale_price' => '15.01',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 145,
                'average_landed_cost' => '11.56',
                'next_po_price' => null,
                'po_price' => '8.11',
                'po_price_expiry' => null,
                'product_id' => 56,
                'taxable' => 1,
                'wholesale_price' => '15.01',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 146,
                'average_landed_cost' => '11.59',
                'next_po_price' => null,
                'po_price' => '8.11',
                'po_price_expiry' => null,
                'product_id' => 55,
                'taxable' => 1,
                'wholesale_price' => '15.01',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 147,
                'average_landed_cost' => '11.90',
                'next_po_price' => null,
                'po_price' => '12.02',
                'po_price_expiry' => null,
                'product_id' => 54,
                'taxable' => 1,
                'wholesale_price' => '15.03',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 148,
                'average_landed_cost' => '6.76',
                'next_po_price' => null,
                'po_price' => '6.95',
                'po_price_expiry' => null,
                'product_id' => 53,
                'taxable' => 1,
                'wholesale_price' => '8.69',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 149,
                'average_landed_cost' => '0.88',
                'next_po_price' => null,
                'po_price' => '0.88',
                'po_price_expiry' => null,
                'product_id' => 52,
                'taxable' => 1,
                'wholesale_price' => '1.19',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 150,
                'average_landed_cost' => '1.02',
                'next_po_price' => null,
                'po_price' => '1.02',
                'po_price_expiry' => null,
                'product_id' => 51,
                'taxable' => 1,
                'wholesale_price' => '1.38',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 151,
                'average_landed_cost' => '1.11',
                'next_po_price' => null,
                'po_price' => '1.11',
                'po_price_expiry' => null,
                'product_id' => 50,
                'taxable' => 1,
                'wholesale_price' => '1.50',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 152,
                'average_landed_cost' => '1.33',
                'next_po_price' => null,
                'po_price' => '1.33',
                'po_price_expiry' => null,
                'product_id' => 49,
                'taxable' => 1,
                'wholesale_price' => '1.80',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 153,
                'average_landed_cost' => '1.11',
                'next_po_price' => null,
                'po_price' => '1.11',
                'po_price_expiry' => null,
                'product_id' => 48,
                'taxable' => 1,
                'wholesale_price' => '1.50',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 154,
                'average_landed_cost' => '1.73',
                'next_po_price' => null,
                'po_price' => '1.73',
                'po_price_expiry' => null,
                'product_id' => 47,
                'taxable' => 1,
                'wholesale_price' => '2.34',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 155,
                'average_landed_cost' => '1.55',
                'next_po_price' => null,
                'po_price' => '1.55',
                'po_price_expiry' => null,
                'product_id' => 46,
                'taxable' => 1,
                'wholesale_price' => '2.10',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 156,
                'average_landed_cost' => '1.33',
                'next_po_price' => null,
                'po_price' => '1.33',
                'po_price_expiry' => null,
                'product_id' => 45,
                'taxable' => 1,
                'wholesale_price' => '1.80',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 157,
                'average_landed_cost' => '1.24',
                'next_po_price' => null,
                'po_price' => '1.24',
                'po_price_expiry' => null,
                'product_id' => 44,
                'taxable' => 1,
                'wholesale_price' => '1.68',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 158,
                'average_landed_cost' => '1.28',
                'next_po_price' => null,
                'po_price' => '1.28',
                'po_price_expiry' => null,
                'product_id' => 43,
                'taxable' => 1,
                'wholesale_price' => '1.73',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 159,
                'average_landed_cost' => '1.02',
                'next_po_price' => null,
                'po_price' => '1.02',
                'po_price_expiry' => null,
                'product_id' => 42,
                'taxable' => 1,
                'wholesale_price' => '1.38',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 160,
                'average_landed_cost' => '1.15',
                'next_po_price' => null,
                'po_price' => '1.15',
                'po_price_expiry' => null,
                'product_id' => 41,
                'taxable' => 1,
                'wholesale_price' => '1.56',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 161,
                'average_landed_cost' => '1.02',
                'next_po_price' => null,
                'po_price' => '1.02',
                'po_price_expiry' => null,
                'product_id' => 40,
                'taxable' => 1,
                'wholesale_price' => '1.38',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 162,
                'average_landed_cost' => '0.75',
                'next_po_price' => null,
                'po_price' => '0.75',
                'po_price_expiry' => null,
                'product_id' => 39,
                'taxable' => 1,
                'wholesale_price' => '1.01',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 163,
                'average_landed_cost' => '0.66',
                'next_po_price' => null,
                'po_price' => '0.66',
                'po_price_expiry' => null,
                'product_id' => 38,
                'taxable' => 1,
                'wholesale_price' => '0.90',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 164,
                'average_landed_cost' => '5.17',
                'next_po_price' => null,
                'po_price' => '5.17',
                'po_price_expiry' => null,
                'product_id' => 37,
                'taxable' => 1,
                'wholesale_price' => '6.99',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 165,
                'average_landed_cost' => '5.17',
                'next_po_price' => null,
                'po_price' => '5.17',
                'po_price_expiry' => null,
                'product_id' => 36,
                'taxable' => 1,
                'wholesale_price' => '6.99',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 166,
                'average_landed_cost' => '5.17',
                'next_po_price' => null,
                'po_price' => '5.17',
                'po_price_expiry' => null,
                'product_id' => 35,
                'taxable' => 1,
                'wholesale_price' => '6.99',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 167,
                'average_landed_cost' => '5.17',
                'next_po_price' => null,
                'po_price' => '5.17',
                'po_price_expiry' => null,
                'product_id' => 34,
                'taxable' => 1,
                'wholesale_price' => '6.99',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 168,
                'average_landed_cost' => '5.17',
                'next_po_price' => null,
                'po_price' => '5.17',
                'po_price_expiry' => null,
                'product_id' => 33,
                'taxable' => 1,
                'wholesale_price' => '6.99',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 169,
                'average_landed_cost' => '5.17',
                'next_po_price' => null,
                'po_price' => '5.17',
                'po_price_expiry' => null,
                'product_id' => 32,
                'taxable' => 1,
                'wholesale_price' => '6.99',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 170,
                'average_landed_cost' => '186.12',
                'next_po_price' => null,
                'po_price' => '186.12',
                'po_price_expiry' => null,
                'product_id' => 31,
                'taxable' => 1,
                'wholesale_price' => '-0.01',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 171,
                'average_landed_cost' => '4.25',
                'next_po_price' => null,
                'po_price' => '4.25',
                'po_price_expiry' => null,
                'product_id' => 30,
                'taxable' => 1,
                'wholesale_price' => '5.74',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 172,
                'average_landed_cost' => '7.50',
                'next_po_price' => null,
                'po_price' => '7.50',
                'po_price_expiry' => null,
                'product_id' => 29,
                'taxable' => 1,
                'wholesale_price' => '10.00',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 173,
                'average_landed_cost' => '7.76',
                'next_po_price' => null,
                'po_price' => '5.39',
                'po_price_expiry' => null,
                'product_id' => 28,
                'taxable' => 1,
                'wholesale_price' => '9.97',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 174,
                'average_landed_cost' => '5.63',
                'next_po_price' => null,
                'po_price' => '4.04',
                'po_price_expiry' => null,
                'product_id' => 27,
                'taxable' => 1,
                'wholesale_price' => '7.47',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 175,
                'average_landed_cost' => '10.04',
                'next_po_price' => null,
                'po_price' => '7.19',
                'po_price_expiry' => null,
                'product_id' => 26,
                'taxable' => 1,
                'wholesale_price' => '13.31',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 176,
                'average_landed_cost' => '12.86',
                'next_po_price' => null,
                'po_price' => '8.99',
                'po_price_expiry' => null,
                'product_id' => 25,
                'taxable' => 1,
                'wholesale_price' => '16.65',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 177,
                'average_landed_cost' => '15.71',
                'next_po_price' => null,
                'po_price' => '11.24',
                'po_price_expiry' => null,
                'product_id' => 24,
                'taxable' => 1,
                'wholesale_price' => '20.81',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 178,
                'average_landed_cost' => '11.98',
                'next_po_price' => null,
                'po_price' => '8.54',
                'po_price_expiry' => null,
                'product_id' => 23,
                'taxable' => 1,
                'wholesale_price' => '15.81',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 179,
                'average_landed_cost' => '12.95',
                'next_po_price' => null,
                'po_price' => '8.99',
                'po_price_expiry' => null,
                'product_id' => 22,
                'taxable' => 1,
                'wholesale_price' => '16.65',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 180,
                'average_landed_cost' => '12.30',
                'next_po_price' => null,
                'po_price' => '8.54',
                'po_price_expiry' => null,
                'product_id' => 21,
                'taxable' => 1,
                'wholesale_price' => '15.81',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 181,
                'average_landed_cost' => '12.32',
                'next_po_price' => null,
                'po_price' => '8.99',
                'po_price_expiry' => null,
                'product_id' => 20,
                'taxable' => 1,
                'wholesale_price' => '16.65',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 182,
                'average_landed_cost' => '12.70',
                'next_po_price' => null,
                'po_price' => '8.99',
                'po_price_expiry' => null,
                'product_id' => 19,
                'taxable' => 1,
                'wholesale_price' => '16.65',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 183,
                'average_landed_cost' => '12.71',
                'next_po_price' => null,
                'po_price' => '8.99',
                'po_price_expiry' => null,
                'product_id' => 18,
                'taxable' => 1,
                'wholesale_price' => '16.65',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 184,
                'average_landed_cost' => '3.05',
                'next_po_price' => null,
                'po_price' => '3.05',
                'po_price_expiry' => null,
                'product_id' => 17,
                'taxable' => 1,
                'wholesale_price' => '4.13',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 185,
                'average_landed_cost' => '4.25',
                'next_po_price' => null,
                'po_price' => '4.25',
                'po_price_expiry' => null,
                'product_id' => 16,
                'taxable' => 1,
                'wholesale_price' => '5.74',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 186,
                'average_landed_cost' => '4.25',
                'next_po_price' => null,
                'po_price' => '4.25',
                'po_price_expiry' => null,
                'product_id' => 15,
                'taxable' => 1,
                'wholesale_price' => '5.74',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 187,
                'average_landed_cost' => '11.07',
                'next_po_price' => null,
                'po_price' => '11.07',
                'po_price_expiry' => null,
                'product_id' => 14,
                'taxable' => 1,
                'wholesale_price' => '14.96',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 188,
                'average_landed_cost' => '11.07',
                'next_po_price' => null,
                'po_price' => '11.07',
                'po_price_expiry' => null,
                'product_id' => 13,
                'taxable' => 1,
                'wholesale_price' => '14.96',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 189,
                'average_landed_cost' => '6.63',
                'next_po_price' => null,
                'po_price' => '6.63',
                'po_price_expiry' => null,
                'product_id' => 12,
                'taxable' => 1,
                'wholesale_price' => '8.96',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 190,
                'average_landed_cost' => '6.63',
                'next_po_price' => null,
                'po_price' => '6.63',
                'po_price_expiry' => null,
                'product_id' => 11,
                'taxable' => 1,
                'wholesale_price' => '8.96',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 191,
                'average_landed_cost' => '6.63',
                'next_po_price' => null,
                'po_price' => '6.63',
                'po_price_expiry' => null,
                'product_id' => 10,
                'taxable' => 1,
                'wholesale_price' => '8.96',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 192,
                'average_landed_cost' => '6.63',
                'next_po_price' => null,
                'po_price' => '6.63',
                'po_price_expiry' => null,
                'product_id' => 9,
                'taxable' => 1,
                'wholesale_price' => '8.96',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 193,
                'average_landed_cost' => '2.64',
                'next_po_price' => null,
                'po_price' => '2.64',
                'po_price_expiry' => null,
                'product_id' => 8,
                'taxable' => 1,
                'wholesale_price' => '3.57',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 194,
                'average_landed_cost' => '7.43',
                'next_po_price' => null,
                'po_price' => '5.39',
                'po_price_expiry' => null,
                'product_id' => 7,
                'taxable' => 1,
                'wholesale_price' => '9.97',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 195,
                'average_landed_cost' => '4.25',
                'next_po_price' => null,
                'po_price' => '4.25',
                'po_price_expiry' => null,
                'product_id' => 6,
                'taxable' => 1,
                'wholesale_price' => '5.74',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 196,
                'average_landed_cost' => '4.25',
                'next_po_price' => null,
                'po_price' => '4.25',
                'po_price_expiry' => null,
                'product_id' => 5,
                'taxable' => 1,
                'wholesale_price' => '5.74',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 197,
                'average_landed_cost' => '4.25',
                'next_po_price' => null,
                'po_price' => '4.25',
                'po_price_expiry' => null,
                'product_id' => 4,
                'taxable' => 1,
                'wholesale_price' => '5.74',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 198,
                'average_landed_cost' => '8.11',
                'next_po_price' => null,
                'po_price' => '5.84',
                'po_price_expiry' => null,
                'product_id' => 3,
                'taxable' => 1,
                'wholesale_price' => '10.81',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 199,
                'average_landed_cost' => '8.41',
                'next_po_price' => null,
                'po_price' => '5.84',
                'po_price_expiry' => null,
                'product_id' => 2,
                'taxable' => 1,
                'wholesale_price' => '11.36',
            ],

            [
                'duty' => '0.00',
                'edlp_discount' => '0.00',
                'id' => 200,
                'average_landed_cost' => '10.06',
                'next_po_price' => null,
                'po_price' => '7.19',
                'po_price_expiry' => null,
                'product_id' => 1,
                'taxable' => 1,
                'wholesale_price' => '13.31',
            ],
        ]);
    }
}
