<?php

namespace Database\Seeders\Development\iseed;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class As400StockDataTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('as400_stock_data')->delete();

        DB::table('as400_stock_data')->insert([

            [
                'description' => 'ACURE-REJUV.DUAL PHASE BAKUCHIOL SERUM20',
                'expected' => '2020-07-29',
                'hide_from_catalogue' => 0,
                'id' => 1,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 20,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-BRIGHTENING VITC SUNSET SERUM 30ML',
                'expected' => '2020-11-23',
                'hide_from_catalogue' => 0,
                'id' => 2,
                'last_received' => '2020-10-21',
                'out_of_stock' => 0,
                'product_id' => 19,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-BIGHT.VIT C &FERULIC ACID SERUM30',
                'expected' => '2020-08-25',
                'hide_from_catalogue' => 0,
                'id' => 3,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 18,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-REJUV.UNDER EYE HYDROGEL MASK12X7M',
                'expected' => '2020-06-16',
                'hide_from_catalogue' => 0,
                'id' => 4,
                'last_received' => '2020-10-26',
                'out_of_stock' => 0,
                'product_id' => 133,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-REJUVENATING SHEET MASK 12X20ML',
                'expected' => '2020-04-02',
                'hide_from_catalogue' => 0,
                'id' => 5,
                'last_received' => '2020-10-26',
                'out_of_stock' => 0,
                'product_id' => 132,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-REJUVENATINGSERUM STICK 30ML',
                'expected' => null,
                'hide_from_catalogue' => 0,
                'id' => 6,
                'last_received' => '2020-06-17',
                'out_of_stock' => 0,
                'product_id' => 128,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-REJUVENATING WHIPPED NGT CREAM 50M',
                'expected' => '2020-04-27',
                'hide_from_catalogue' => 0,
                'id' => 7,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 129,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-REJUVENATINGWITCH HAZEL TONER59M',
                'expected' => '2020-11-18',
                'hide_from_catalogue' => 0,
                'id' => 8,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 3,
                'status' => 'A',
            ],

            [
                'description' => '**URE-SOOTHING ROSEWATER/WATERM MIST 59M',
                'expected' => null,
                'hide_from_catalogue' => 0,
                'id' => 9,
                'last_received' => '0001-01-01',
                'out_of_stock' => 1,
                'product_id' => 2,
                'status' => 'D',
            ],

            [
                'description' => 'ACURE-INCREDIBLY CLEAR SHEET MASK 12X20M',
                'expected' => '2020-11-12',
                'hide_from_catalogue' => 0,
                'id' => 10,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 131,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-CONDITIONER VOLUME PEPPERMINT236ML',
                'expected' => '2020-11-18',
                'hide_from_catalogue' => 0,
                'id' => 11,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 71,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-SHAMPOO VOLUMEPEPPERMINT 236ML',
                'expected' => '2020-06-17',
                'hide_from_catalogue' => 0,
                'id' => 12,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 70,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-COND.SIMPLY SMOOTHING-COCONUT236ML',
                'expected' => '2020-04-14',
                'hide_from_catalogue' => 0,
                'id' => 13,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 69,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-SHAMP.SIMPLY SMOOTHING COCONUT236M',
                'expected' => '2020-11-10',
                'hide_from_catalogue' => 0,
                'id' => 14,
                'last_received' => '2020-10-15',
                'out_of_stock' => 0,
                'product_id' => 68,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-COND. CLARIFYING-LEMONGRASS 236ML',
                'expected' => '2020-11-10',
                'hide_from_catalogue' => 0,
                'id' => 15,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 67,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-SHAMPOO CLARIFYING LEMONGRASS236ML',
                'expected' => '2020-08-12',
                'hide_from_catalogue' => 0,
                'id' => 16,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 66,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-COND.ULTRA HYDRATING ARGAN 236ML',
                'expected' => '2020-06-10',
                'hide_from_catalogue' => 0,
                'id' => 17,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 65,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-SHAMPOO ULTR HYDRATING ARGAN 236ML',
                'expected' => '2020-11-10',
                'hide_from_catalogue' => 0,
                'id' => 18,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 64,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-SHAMPOO UNICORN SHIMMER 236ML',
                'expected' => '2020-11-16',
                'hide_from_catalogue' => 0,
                'id' => 19,
                'last_received' => '2020-10-02',
                'out_of_stock' => 0,
                'product_id' => 28,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-BRIGHTENING GLOW LOTION 237ML',
                'expected' => '2020-11-11',
                'hide_from_catalogue' => 0,
                'id' => 20,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 125,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-SOOTHING 24HRMOISTURE LOTION 237M',
                'expected' => '2020-03-18',
                'hide_from_catalogue' => 0,
                'id' => 21,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 124,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-SHAMPOO BAR COCONUT&ARGAN  140G',
                'expected' => '2020-06-25',
                'hide_from_catalogue' => 0,
                'id' => 22,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 27,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-IONIC BLONDECONDITIONER 237ML',
                'expected' => '2020-11-10',
                'hide_from_catalogue' => 0,
                'id' => 23,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 7,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-CLEAR CHARCOALLEMONADE MASK 50ML',
                'expected' => '2020-11-17',
                'hide_from_catalogue' => 0,
                'id' => 24,
                'last_received' => '2020-11-13',
                'out_of_stock' => 0,
                'product_id' => 26,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-CHARCOAL UNDEREYE HYDROGELS 12X7ML',
                'expected' => null,
                'hide_from_catalogue' => 0,
                'id' => 25,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 130,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-CLEAR CHARCOALCLEANSING CLAY 118ML',
                'expected' => '2020-11-17',
                'hide_from_catalogue' => 0,
                'id' => 26,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 127,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-CLEAR CHARCOALFACIAL SCRUB 118ML',
                'expected' => '2020-06-20',
                'hide_from_catalogue' => 0,
                'id' => 27,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 126,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-SOOTHING BIOCELLULOSE GELMASK12X20',
                'expected' => '2020-02-13',
                'hide_from_catalogue' => 0,
                'id' => 28,
                'last_received' => '2020-10-21',
                'out_of_stock' => 0,
                'product_id' => 135,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-SOOTHING MICELLAR TOWLETTES TRAY',
                'expected' => '2019-10-30',
                'hide_from_catalogue' => 0,
                'id' => 29,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 200,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-SOOTHING UNDEREYE HYDROGEL 12X7ML',
                'expected' => '2020-04-02',
                'hide_from_catalogue' => 0,
                'id' => 30,
                'last_received' => '2020-10-26',
                'out_of_stock' => 0,
                'product_id' => 134,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-BRIGHT.UNDER EYE HYDROGEL 12X7ML',
                'expected' => '2020-01-31',
                'hide_from_catalogue' => 0,
                'id' => 31,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 136,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-BRIGHT.BIOCELLULOSE GEL MASK12X20M',
                'expected' => null,
                'hide_from_catalogue' => 0,
                'id' => 32,
                'last_received' => '2020-10-26',
                'out_of_stock' => 0,
                'product_id' => 137,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-BRIGHTENING SUPER GREENS SERUM 30M',
                'expected' => '2020-11-11',
                'hide_from_catalogue' => 0,
                'id' => 33,
                'last_received' => '2020-10-30',
                'out_of_stock' => 0,
                'product_id' => 138,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-DEODORANT LAVENDER&COCONUT 62G',
                'expected' => '2019-11-12',
                'hide_from_catalogue' => 0,
                'id' => 34,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 123,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-DEODORANT LEMON VERBENA 62G',
                'expected' => '2020-11-04',
                'hide_from_catalogue' => 0,
                'id' => 35,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 122,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-DEODORANT CEDARWOOD & MINT 62G',
                'expected' => '2020-08-07',
                'hide_from_catalogue' => 0,
                'id' => 36,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 121,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-DEODORANT FRAGRANCE FREE\\62G',
                'expected' => '2020-11-17',
                'hide_from_catalogue' => 0,
                'id' => 37,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 120,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-BRIGHTENINGBODY SCRUB 177ML',
                'expected' => '2020-11-10',
                'hide_from_catalogue' => 0,
                'id' => 38,
                'last_received' => '2020-11-13',
                'out_of_stock' => 0,
                'product_id' => 1,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-RESURF.INTER-GLY-LACTIC SERUM 20ML',
                'expected' => '2020-06-16',
                'hide_from_catalogue' => 0,
                'id' => 39,
                'last_received' => '2020-10-08',
                'out_of_stock' => 0,
                'product_id' => 25,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-RESURF.OVERNIGHT GLYCOLIC TRMT30ML',
                'expected' => '2020-11-17',
                'hide_from_catalogue' => 0,
                'id' => 40,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 24,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-RESURF.DEWY ALL DAY MOISTURIZER30M',
                'expected' => '2020-11-17',
                'hide_from_catalogue' => 0,
                'id' => 41,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 23,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-HYDRATING EYECREAM 14.7ML',
                'expected' => '2020-11-10',
                'hide_from_catalogue' => 0,
                'id' => 42,
                'last_received' => '2020-10-02',
                'out_of_stock' => 0,
                'product_id' => 22,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-HYDRATING 12HOUR MOISTURIZER30ML',
                'expected' => '2020-11-17',
                'hide_from_catalogue' => 0,
                'id' => 43,
                'last_received' => '2020-10-02',
                'out_of_stock' => 0,
                'product_id' => 21,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-FORTIFYING SILVER MASK TRAY 12X20M',
                'expected' => null,
                'hide_from_catalogue' => 0,
                'id' => 44,
                'last_received' => '2020-06-04',
                'out_of_stock' => 0,
                'product_id' => 63,
                'status' => 'A',
            ],

            [
                'description' => 'ACURE-FIRMING GOLDFOIL MASKTRAY 12X20M',
                'expected' => null,
                'hide_from_catalogue' => 0,
                'id' => 45,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 62,
                'status' => 'A',
            ],

            [
                'description' => 'ANDALOU-ROSEMARY+LEMON BALM SHAVE CRM236',
                'expected' => '2020-11-15',
                'hide_from_catalogue' => 0,
                'id' => 46,
                'last_received' => '2020-11-03',
                'out_of_stock' => 0,
                'product_id' => 149,
                'status' => 'A',
            ],

            [
                'description' => 'ANDALOU-ROSE POMEGR.SHAVE CREAM 236ML',
                'expected' => '2019-12-10',
                'hide_from_catalogue' => 0,
                'id' => 47,
                'last_received' => '2020-11-03',
                'out_of_stock' => 0,
                'product_id' => 148,
                'status' => 'A',
            ],

            [
                'description' => 'ANDALOU-LAVENDER THYME SHAVE CREAM 236ML',
                'expected' => '2020-11-30',
                'hide_from_catalogue' => 0,
                'id' => 48,
                'last_received' => '2020-11-03',
                'out_of_stock' => 0,
                'product_id' => 147,
                'status' => 'A',
            ],

            [
                'description' => 'ANDALOU-COCONUT LIMESHAVE CREAM 236ML',
                'expected' => '2019-12-10',
                'hide_from_catalogue' => 0,
                'id' => 49,
                'last_received' => '2020-11-05',
                'out_of_stock' => 0,
                'product_id' => 146,
                'status' => 'A',
            ],

            [
                'description' => 'ANDALOU-LAV.THYME BOTANICAL DEOD 75G',
                'expected' => '2020-11-11',
                'hide_from_catalogue' => 0,
                'id' => 50,
                'last_received' => '2020-10-28',
                'out_of_stock' => 0,
                'product_id' => 145,
                'status' => 'A',
            ],

            [
                'description' => 'ANDALOU-COCONUT LIMEBOTTANICAL DEOD 75G',
                'expected' => '2020-11-15',
                'hide_from_catalogue' => 0,
                'id' => 51,
                'last_received' => '2020-11-12',
                'out_of_stock' => 0,
                'product_id' => 144,
                'status' => 'A',
            ],

            [
                'description' => 'ANDALOU-ROSE POMEGR.BOTTANICAL DEOD 75G',
                'expected' => '2020-11-15',
                'hide_from_catalogue' => 0,
                'id' => 52,
                'last_received' => '2020-11-13',
                'out_of_stock' => 0,
                'product_id' => 143,
                'status' => 'A',
            ],

            [
                'description' => 'ANDALOU-LVNDER THYMEREFRESHING BL 946ML',
                'expected' => '2020-02-04',
                'hide_from_catalogue' => 0,
                'id' => 53,
                'last_received' => '2020-11-13',
                'out_of_stock' => 0,
                'product_id' => 58,
                'status' => 'A',
            ],

            [
                'description' => 'ANDALOU-LVNDER THYMEREFRESHING SG 946ML',
                'expected' => '2020-02-04',
                'hide_from_catalogue' => 0,
                'id' => 54,
                'last_received' => '2020-09-11',
                'out_of_stock' => 0,
                'product_id' => 57,
                'status' => 'A',
            ],

            [
                'description' => 'ANDALOU-CANNACELL DEOD ROSEMARY LEMON75G',
                'expected' => '2020-10-30',
                'hide_from_catalogue' => 0,
                'id' => 55,
                'last_received' => '2020-09-26',
                'out_of_stock' => 0,
                'product_id' => 139,
                'status' => 'A',
            ],

            [
                'description' => 'ANDALOU-1000 ROSESSOOTHING BL 946ML',
                'expected' => '2020-02-04',
                'hide_from_catalogue' => 0,
                'id' => 56,
                'last_received' => '2020-08-12',
                'out_of_stock' => 0,
                'product_id' => 60,
                'status' => 'A',
            ],

            [
                'description' => 'ANDALOU-1000 ROSESSOOTHING SHOWGEL946M',
                'expected' => '2020-02-04',
                'hide_from_catalogue' => 0,
                'id' => 57,
                'last_received' => '2020-09-11',
                'out_of_stock' => 0,
                'product_id' => 59,
                'status' => 'A',
            ],

            [
                'description' => 'ANDALOU-MOISTURE RICH ARGAN OIL&SHEACOND',
                'expected' => '2020-02-04',
                'hide_from_catalogue' => 0,
                'id' => 58,
                'last_received' => '2020-09-11',
                'out_of_stock' => 0,
                'product_id' => 56,
                'status' => 'A',
            ],

            [
                'description' => 'ANDALOU-MOISTURE RICH ARGAN OIL&SHEASHAM',
                'expected' => '2020-02-04',
                'hide_from_catalogue' => 0,
                'id' => 59,
                'last_received' => '2020-09-11',
                'out_of_stock' => 0,
                'product_id' => 55,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-ALL PURPOSECLEANER 4L CITR/ZES',
                'expected' => '2020-03-31',
                'hide_from_catalogue' => 0,
                'id' => 60,
                'last_received' => '2020-11-09',
                'out_of_stock' => 0,
                'product_id' => 158,
                'status' => 'A',
            ],

            [
                'description' => '**ATTITUDE-BATHROOMCLEANER 4L',
                'expected' => '2019-10-29',
                'hide_from_catalogue' => 0,
                'id' => 61,
                'last_received' => '2020-04-01',
                'out_of_stock' => 1,
                'product_id' => 157,
                'status' => 'D',
            ],

            [
                'description' => 'ATTITUDE-DISINFECTANT 99.9%  4L',
                'expected' => '2020-01-27',
                'hide_from_catalogue' => 0,
                'id' => 62,
                'last_received' => '2020-11-11',
                'out_of_stock' => 0,
                'product_id' => 156,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-LAUNDRY DETWILDFLOWERS (160) 4L',
                'expected' => '2019-11-26',
                'hide_from_catalogue' => 0,
                'id' => 63,
                'last_received' => '2020-10-21',
                'out_of_stock' => 0,
                'product_id' => 155,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-DISHWASHINGLIQ CITRUS ZEST 4L',
                'expected' => '2020-01-27',
                'hide_from_catalogue' => 0,
                'id' => 64,
                'last_received' => '2020-09-29',
                'out_of_stock' => 0,
                'product_id' => 154,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-UNSCENTED LUNDRY DET (160) 4L',
                'expected' => '2019-10-29',
                'hide_from_catalogue' => 0,
                'id' => 65,
                'last_received' => '2020-11-11',
                'out_of_stock' => 0,
                'product_id' => 97,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-LAUNDRY DETCITRUS ZEST(160) 4L',
                'expected' => '2020-10-29',
                'hide_from_catalogue' => 0,
                'id' => 66,
                'last_received' => '2020-10-21',
                'out_of_stock' => 0,
                'product_id' => 96,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-LAUNDRY DETPINK GRPFRT(160) 4L',
                'expected' => '2020-11-09',
                'hide_from_catalogue' => 0,
                'id' => 67,
                'last_received' => '2020-10-21',
                'out_of_stock' => 0,
                'product_id' => 95,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-DISHWASHINGLIQ GRN APPL&BASIL4L',
                'expected' => '2019-10-14',
                'hide_from_catalogue' => 0,
                'id' => 68,
                'last_received' => '2020-11-11',
                'out_of_stock' => 0,
                'product_id' => 91,
                'status' => 'A',
            ],

            [
                'description' => '**TITUDE-DISHWASHINGLIQ CORIAND&OLIVE 4L',
                'expected' => '2020-07-10',
                'hide_from_catalogue' => 0,
                'id' => 69,
                'last_received' => '2020-08-12',
                'out_of_stock' => 0,
                'product_id' => 90,
                'status' => 'D',
            ],

            [
                'description' => '**TITUDE-DISHWASHINGLIQ PINK GRPFRUIT 4L',
                'expected' => '2019-10-14',
                'hide_from_catalogue' => 0,
                'id' => 70,
                'last_received' => '2020-07-13',
                'out_of_stock' => 0,
                'product_id' => 89,
                'status' => 'D',
            ],

            [
                'description' => 'ATTITUDE-LAUNDRY DETPINK GRPFRUIT(80)2L',
                'expected' => '2019-10-14',
                'hide_from_catalogue' => 0,
                'id' => 71,
                'last_received' => '2020-06-01',
                'out_of_stock' => 0,
                'product_id' => 78,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-LAUNDRY DETWILDFLOWERS (80) 2L',
                'expected' => '2019-10-14',
                'hide_from_catalogue' => 0,
                'id' => 72,
                'last_received' => '2020-07-15',
                'out_of_stock' => 0,
                'product_id' => 77,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-DISH LIQUIDBABY BOTTLES FF 2L',
                'expected' => '2020-05-06',
                'hide_from_catalogue' => 0,
                'id' => 73,
                'last_received' => '2020-10-23',
                'out_of_stock' => 0,
                'product_id' => 61,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-UNSCENTEDLAUNDRY DET(80)2LBOX',
                'expected' => '2020-11-17',
                'hide_from_catalogue' => 0,
                'id' => 74,
                'last_received' => '2020-11-04',
                'out_of_stock' => 0,
                'product_id' => 14,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-LAUDRY DETCITRUS ZEST(80) 2L',
                'expected' => '2020-11-17',
                'hide_from_catalogue' => 0,
                'id' => 75,
                'last_received' => '2020-11-04',
                'out_of_stock' => 0,
                'product_id' => 13,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-UNSCENTED DISHWASHING LIQ 2LBOX',
                'expected' => '2020-10-09',
                'hide_from_catalogue' => 0,
                'id' => 76,
                'last_received' => '0001-01-01',
                'out_of_stock' => 0,
                'product_id' => 12,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-DISHWASHINGLIQ GRN APP&BASL 2L',
                'expected' => '2020-10-09',
                'hide_from_catalogue' => 0,
                'id' => 77,
                'last_received' => '0001-01-01',
                'out_of_stock' => 0,
                'product_id' => 11,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-KITCHENCLEANER 2L BOX',
                'expected' => '2020-11-20',
                'hide_from_catalogue' => 0,
                'id' => 78,
                'last_received' => '2020-11-04',
                'out_of_stock' => 0,
                'product_id' => 10,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-FLOOR SURFACE CLNR TILES&WOOD2L',
                'expected' => '2020-07-13',
                'hide_from_catalogue' => 0,
                'id' => 79,
                'last_received' => '2020-11-11',
                'out_of_stock' => 0,
                'product_id' => 9,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-HAND SANITIZER-LEMON LEAVES100M',
                'expected' => '2020-06-17',
                'hide_from_catalogue' => 0,
                'id' => 80,
                'last_received' => '2020-06-12',
                'out_of_stock' => 0,
                'product_id' => 30,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-HAND SANITIZER-ORANGELEAVES100M',
                'expected' => '2020-07-10',
                'hide_from_catalogue' => 0,
                'id' => 81,
                'last_received' => '2020-11-11',
                'out_of_stock' => 0,
                'product_id' => 16,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-HAND SANITIZER-OLIVE LEAVES100M',
                'expected' => '2020-07-10',
                'hide_from_catalogue' => 0,
                'id' => 82,
                'last_received' => '2020-11-11',
                'out_of_stock' => 0,
                'product_id' => 15,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-DISINFECTANT 99.9% THYME&LAV800',
                'expected' => '2020-07-21',
                'hide_from_catalogue' => 0,
                'id' => 83,
                'last_received' => '2020-11-09',
                'out_of_stock' => 0,
                'product_id' => 8,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-DISINFECT.99.9% THYME&CIT2LBOX',
                'expected' => '2019-10-29',
                'hide_from_catalogue' => 0,
                'id' => 84,
                'last_received' => '2020-06-24',
                'out_of_stock' => 0,
                'product_id' => 94,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-BATHROOM CLEANER-CITRUS ZEST 2L',
                'expected' => '2019-10-29',
                'hide_from_catalogue' => 0,
                'id' => 85,
                'last_received' => '2020-11-13',
                'out_of_stock' => 0,
                'product_id' => 80,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-ALL PURPOSECLNR CITRUS ZEST 2L',
                'expected' => '2019-10-29',
                'hide_from_catalogue' => 0,
                'id' => 86,
                'last_received' => '2020-10-21',
                'out_of_stock' => 0,
                'product_id' => 79,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-DISHWASHINGLIQ BABYBOTTLES FF1L',
                'expected' => '2020-11-20',
                'hide_from_catalogue' => 0,
                'id' => 87,
                'last_received' => '2020-11-04',
                'out_of_stock' => 0,
                'product_id' => 198,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-DISHWASHINGLIQ CITRUS ZEST 2L',
                'expected' => '2019-10-29',
                'hide_from_catalogue' => 0,
                'id' => 88,
                'last_received' => '2020-10-21',
                'out_of_stock' => 0,
                'product_id' => 93,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-DISHWASHINGLIQ PINK GRPFRUIT 2L',
                'expected' => '2019-10-29',
                'hide_from_catalogue' => 0,
                'id' => 89,
                'last_received' => '2020-09-29',
                'out_of_stock' => 0,
                'product_id' => 92,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-AIR PURIFIER CORIANDER&OLIVE227',
                'expected' => '2020-10-09',
                'hide_from_catalogue' => 0,
                'id' => 90,
                'last_received' => '2020-09-22',
                'out_of_stock' => 0,
                'product_id' => 197,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-AIR PURIFIER GRNAPPLE&BASIL227G',
                'expected' => '2019-10-14',
                'hide_from_catalogue' => 0,
                'id' => 91,
                'last_received' => '2020-11-09',
                'out_of_stock' => 0,
                'product_id' => 196,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-FOAMING HAND SOAP-MANGO 295ML',
                'expected' => '2020-06-05',
                'hide_from_catalogue' => 0,
                'id' => 92,
                'last_received' => '2020-11-03',
                'out_of_stock' => 0,
                'product_id' => 195,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-FOAMING HAND SOAP-WTRMELON&COCO',
                'expected' => '2020-03-17',
                'hide_from_catalogue' => 0,
                'id' => 93,
                'last_received' => '2020-11-09',
                'out_of_stock' => 0,
                'product_id' => 194,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-FOAMING HAND SOAP-BLUEBERRY295M',
                'expected' => '2020-09-01',
                'hide_from_catalogue' => 0,
                'id' => 94,
                'last_received' => '2020-10-23',
                'out_of_stock' => 0,
                'product_id' => 193,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-FOAMING HAND SOAP-VAN&PEAR 295M',
                'expected' => '2020-03-31',
                'hide_from_catalogue' => 0,
                'id' => 95,
                'last_received' => '2020-11-04',
                'out_of_stock' => 0,
                'product_id' => 192,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-HAND SANITIZER-MANGO 100ML',
                'expected' => '2020-11-20',
                'hide_from_catalogue' => 0,
                'id' => 96,
                'last_received' => '2020-11-11',
                'out_of_stock' => 0,
                'product_id' => 6,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-HAND SANITIZER-WATERMELON COCNT',
                'expected' => '2020-11-17',
                'hide_from_catalogue' => 0,
                'id' => 97,
                'last_received' => '2020-11-11',
                'out_of_stock' => 0,
                'product_id' => 5,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-HAND SANITIZER-VAN.&PEAR 100ML',
                'expected' => '2020-11-17',
                'hide_from_catalogue' => 0,
                'id' => 98,
                'last_received' => '2020-11-11',
                'out_of_stock' => 0,
                'product_id' => 4,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-AFTER SUNMELT-IN GEL 150G',
                'expected' => '2020-03-31',
                'hide_from_catalogue' => 0,
                'id' => 99,
                'last_received' => '2020-08-27',
                'out_of_stock' => 0,
                'product_id' => 191,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-SPF30 ADULTSENSITIVE SKIN 150G',
                'expected' => '2020-08-27',
                'hide_from_catalogue' => 0,
                'id' => 100,
                'last_received' => '2020-08-24',
                'out_of_stock' => 0,
                'product_id' => 190,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-SPF30 FACESUNSCREEN FF 75G',
                'expected' => '2020-07-20',
                'hide_from_catalogue' => 0,
                'id' => 101,
                'last_received' => '2020-09-29',
                'out_of_stock' => 0,
                'product_id' => 189,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-FOAMING HAND SOAP-ORANGLEAVE295',
                'expected' => '2019-10-14',
                'hide_from_catalogue' => 0,
                'id' => 102,
                'last_received' => '2020-11-11',
                'out_of_stock' => 0,
                'product_id' => 188,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-FOAMING HAND SOAP-WHITETEALEAVE',
                'expected' => '2020-11-20',
                'hide_from_catalogue' => 0,
                'id' => 103,
                'last_received' => '2020-11-09',
                'out_of_stock' => 0,
                'product_id' => 187,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-FOAMING HAND SOAP-RED VINE LEAV',
                'expected' => '2020-07-29',
                'hide_from_catalogue' => 0,
                'id' => 104,
                'last_received' => '2020-11-11',
                'out_of_stock' => 0,
                'product_id' => 186,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-FOAMING HAND SOAP-OLIVE LEAV295',
                'expected' => '2020-05-06',
                'hide_from_catalogue' => 0,
                'id' => 105,
                'last_received' => '2020-11-11',
                'out_of_stock' => 0,
                'product_id' => 185,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-FOAMING HAND SOAP-LEMON LEAV295',
                'expected' => '2020-05-06',
                'hide_from_catalogue' => 0,
                'id' => 106,
                'last_received' => '2020-11-09',
                'out_of_stock' => 0,
                'product_id' => 184,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-HAND SOAP-ORANGE LEAVES 4L',
                'expected' => '2020-03-27',
                'hide_from_catalogue' => 0,
                'id' => 107,
                'last_received' => '2020-10-27',
                'out_of_stock' => 0,
                'product_id' => 164,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-BODY LOTION-GLOWING 473ML',
                'expected' => '2020-09-30',
                'hide_from_catalogue' => 0,
                'id' => 108,
                'last_received' => '2020-11-11',
                'out_of_stock' => 0,
                'product_id' => 115,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-BODY LOTION-REGENERATING 473ML',
                'expected' => '2020-04-24',
                'hide_from_catalogue' => 0,
                'id' => 109,
                'last_received' => '2020-11-04',
                'out_of_stock' => 0,
                'product_id' => 114,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-BODY LOTION-SOOTHING 473ML',
                'expected' => '2020-07-08',
                'hide_from_catalogue' => 0,
                'id' => 110,
                'last_received' => '2020-09-29',
                'out_of_stock' => 0,
                'product_id' => 113,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-BODY LOTION-ENERGIZING 473ML',
                'expected' => '2020-07-08',
                'hide_from_catalogue' => 0,
                'id' => 111,
                'last_received' => '2020-11-09',
                'out_of_stock' => 0,
                'product_id' => 112,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-BODY LOTION-NOURISHING 473ML',
                'expected' => '2020-09-15',
                'hide_from_catalogue' => 0,
                'id' => 112,
                'last_received' => '2020-11-11',
                'out_of_stock' => 0,
                'product_id' => 111,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-BODY LOTION-CHAMOMILE 473ML',
                'expected' => '2020-11-17',
                'hide_from_catalogue' => 0,
                'id' => 113,
                'last_received' => '2020-09-22',
                'out_of_stock' => 0,
                'product_id' => 110,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-BODY LOTION-AVOCADO 473ML',
                'expected' => '2020-04-24',
                'hide_from_catalogue' => 0,
                'id' => 114,
                'last_received' => '2020-09-29',
                'out_of_stock' => 0,
                'product_id' => 109,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-BODY LOTION-ARGAN 473ML',
                'expected' => '2020-03-24',
                'hide_from_catalogue' => 0,
                'id' => 115,
                'last_received' => '2020-11-13',
                'out_of_stock' => 0,
                'product_id' => 108,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-BODY LOTION-FRAG FREE 473ML',
                'expected' => '2020-04-24',
                'hide_from_catalogue' => 0,
                'id' => 116,
                'last_received' => '2020-09-29',
                'out_of_stock' => 0,
                'product_id' => 98,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-BODY CREAM-CHAMOMILE 240ML',
                'expected' => '2020-12-01',
                'hide_from_catalogue' => 0,
                'id' => 117,
                'last_received' => '2020-08-10',
                'out_of_stock' => 0,
                'product_id' => 99,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-BODY CREAM-AVOCADO 240ML',
                'expected' => '2020-06-19',
                'hide_from_catalogue' => 0,
                'id' => 118,
                'last_received' => '2020-08-19',
                'out_of_stock' => 0,
                'product_id' => 100,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-BODY CREAM-ARGAN 240ML',
                'expected' => '2020-11-20',
                'hide_from_catalogue' => 0,
                'id' => 119,
                'last_received' => '2020-09-29',
                'out_of_stock' => 0,
                'product_id' => 101,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-BODY CREAM-FRAG FREE 240ML',
                'expected' => '2020-07-08',
                'hide_from_catalogue' => 0,
                'id' => 120,
                'last_received' => '2020-10-27',
                'out_of_stock' => 0,
                'product_id' => 102,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-HAND SOAP-CHAMOMILE 473ML',
                'expected' => '2020-05-13',
                'hide_from_catalogue' => 0,
                'id' => 121,
                'last_received' => '2020-11-11',
                'out_of_stock' => 0,
                'product_id' => 103,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-HAND SOAP-AVOCADO 473ML',
                'expected' => '2020-05-06',
                'hide_from_catalogue' => 0,
                'id' => 122,
                'last_received' => '2020-11-09',
                'out_of_stock' => 0,
                'product_id' => 104,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-HAND SOAP-ARGAN 473ML',
                'expected' => '2020-12-01',
                'hide_from_catalogue' => 0,
                'id' => 123,
                'last_received' => '2020-11-11',
                'out_of_stock' => 0,
                'product_id' => 105,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-HAND SOAP-FRAG FREEM-CHAM.473M',
                'expected' => '2020-03-23',
                'hide_from_catalogue' => 0,
                'id' => 124,
                'last_received' => '2020-11-03',
                'out_of_stock' => 0,
                'product_id' => 106,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-DEODORANT-ORANGE LEAVES 85G',
                'expected' => '2020-03-17',
                'hide_from_catalogue' => 0,
                'id' => 125,
                'last_received' => '2020-11-12',
                'out_of_stock' => 0,
                'product_id' => 37,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-DEODORANT-WHITE TEA LEAVES 85G',
                'expected' => '2020-03-17',
                'hide_from_catalogue' => 0,
                'id' => 126,
                'last_received' => '2020-09-29',
                'out_of_stock' => 0,
                'product_id' => 36,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-DEODORANT-RED VINE LEAVES 85G',
                'expected' => '2020-03-17',
                'hide_from_catalogue' => 0,
                'id' => 127,
                'last_received' => '2020-11-13',
                'out_of_stock' => 0,
                'product_id' => 35,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-DEODORANT-OLIVE LEAVES 85G',
                'expected' => '2020-03-17',
                'hide_from_catalogue' => 0,
                'id' => 128,
                'last_received' => '2020-11-12',
                'out_of_stock' => 0,
                'product_id' => 34,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-DEODORANT-LEMON LEAVES 85G',
                'expected' => '2020-03-17',
                'hide_from_catalogue' => 0,
                'id' => 129,
                'last_received' => '2020-11-12',
                'out_of_stock' => 0,
                'product_id' => 33,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-DEODORANT-UNSCENTED 85G',
                'expected' => '2020-03-17',
                'hide_from_catalogue' => 0,
                'id' => 130,
                'last_received' => '2020-11-09',
                'out_of_stock' => 0,
                'product_id' => 32,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-2IN1 FOAMING WASH ORGNPOM.295ML',
                'expected' => '2020-03-31',
                'hide_from_catalogue' => 0,
                'id' => 131,
                'last_received' => '2020-11-04',
                'out_of_stock' => 0,
                'product_id' => 179,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-2IN1 FOAMING WASH PEARNECT295ML',
                'expected' => null,
                'hide_from_catalogue' => 0,
                'id' => 132,
                'last_received' => '2020-11-09',
                'out_of_stock' => 0,
                'product_id' => 180,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-2IN1 FOAMING WASH ALMDMILK295ML',
                'expected' => '2020-06-05',
                'hide_from_catalogue' => 0,
                'id' => 133,
                'last_received' => '2020-09-29',
                'out_of_stock' => 0,
                'product_id' => 181,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-2IN1 FOAMING WASH SWTAPPLE295ML',
                'expected' => '2020-11-21',
                'hide_from_catalogue' => 0,
                'id' => 134,
                'last_received' => '2020-10-23',
                'out_of_stock' => 0,
                'product_id' => 182,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-2IN1 FOAMING WASH FRAGFREE295ML',
                'expected' => '2020-03-31',
                'hide_from_catalogue' => 0,
                'id' => 135,
                'last_received' => '2020-10-27',
                'out_of_stock' => 0,
                'product_id' => 183,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-HAND SOAP-LEMON LEAVES 4L',
                'expected' => '2019-05-10',
                'hide_from_catalogue' => 0,
                'id' => 136,
                'last_received' => '2020-11-04',
                'out_of_stock' => 0,
                'product_id' => 163,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-SHAMPOO -VOLUME&SHINE 4L',
                'expected' => '2019-05-10',
                'hide_from_catalogue' => 0,
                'id' => 137,
                'last_received' => '2020-06-18',
                'out_of_stock' => 0,
                'product_id' => 162,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-SHAMPOO-NOURISHING&STRENGTH 4L',
                'expected' => '2020-11-17',
                'hide_from_catalogue' => 0,
                'id' => 138,
                'last_received' => '2020-08-12',
                'out_of_stock' => 0,
                'product_id' => 161,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-HAND SOAP-LEMON LEAVES 2L BOX',
                'expected' => '2019-10-29',
                'hide_from_catalogue' => 0,
                'id' => 139,
                'last_received' => '2020-10-30',
                'out_of_stock' => 0,
                'product_id' => 88,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-HAND SOAP-OLIVE LEAVES 2L BOX',
                'expected' => '2019-10-29',
                'hide_from_catalogue' => 0,
                'id' => 140,
                'last_received' => '2020-11-11',
                'out_of_stock' => 0,
                'product_id' => 87,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-HAND SOAP-ORANGE LEAVES 2L BOX',
                'expected' => '2019-10-29',
                'hide_from_catalogue' => 0,
                'id' => 141,
                'last_received' => '2020-11-04',
                'out_of_stock' => 0,
                'product_id' => 86,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-SHAMPOO-NOURISH&STRNGTH 2L BOX',
                'expected' => '2019-10-29',
                'hide_from_catalogue' => 0,
                'id' => 142,
                'last_received' => '2020-05-13',
                'out_of_stock' => 0,
                'product_id' => 85,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-SHAMPOO-COLOR PROTECTION 2L BOX',
                'expected' => '2019-10-29',
                'hide_from_catalogue' => 0,
                'id' => 143,
                'last_received' => '2020-04-23',
                'out_of_stock' => 0,
                'product_id' => 84,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-SHAMPOO-VOLUME & SHINE 2L BOX',
                'expected' => '2019-10-29',
                'hide_from_catalogue' => 0,
                'id' => 144,
                'last_received' => '2020-10-21',
                'out_of_stock' => 0,
                'product_id' => 83,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-BODY WASH-SOOTHING 2L BOX',
                'expected' => '2019-10-29',
                'hide_from_catalogue' => 0,
                'id' => 145,
                'last_received' => '2020-11-11',
                'out_of_stock' => 0,
                'product_id' => 82,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-BODY WASH-ENERGIZING 2L BOX',
                'expected' => '2019-10-29',
                'hide_from_catalogue' => 0,
                'id' => 146,
                'last_received' => '2020-10-30',
                'out_of_stock' => 0,
                'product_id' => 81,
                'status' => 'A',
            ],

            [
                'description' => '**TITUDE-SPF30 SUNCARE DSPLY BABY&KID72P',
                'expected' => null,
                'hide_from_catalogue' => 0,
                'id' => 147,
                'last_received' => '0001-01-01',
                'out_of_stock' => 1,
                'product_id' => 178,
                'status' => 'D',
            ],

            [
                'description' => '**TITUDE-SPF30 SUNCARE DSPY BABY&ADULT72',
                'expected' => '2020-04-13',
                'hide_from_catalogue' => 0,
                'id' => 148,
                'last_received' => '0001-01-01',
                'out_of_stock' => 1,
                'product_id' => 177,
                'status' => 'D',
            ],

            [
                'description' => 'ATTITUDE-SPF30 SUNCARE DSPY ADULT 72UNIT',
                'expected' => null,
                'hide_from_catalogue' => 0,
                'id' => 149,
                'last_received' => '0001-01-01',
                'out_of_stock' => 0,
                'product_id' => 176,
                'status' => 'A',
            ],

            [
                'description' => 'ATTITUDE-DEODORANTFLOOR DISPLAY 36PC',
                'expected' => '2020-03-30',
                'hide_from_catalogue' => 0,
                'id' => 150,
                'last_received' => '0001-01-01',
                'out_of_stock' => 0,
                'product_id' => 31,
                'status' => 'S',
            ],

            [
                'description' => 'DIVINE-SPRUCE-BLACK(ORGANIC) 100ML',
                'expected' => null,
                'hide_from_catalogue' => 0,
                'id' => 151,
                'last_received' => '2019-12-04',
                'out_of_stock' => 0,
                'product_id' => 140,
                'status' => 'A',
            ],

            [
                'description' => 'DIVINE-FIR BALSAM(ORGANIC) 30ML',
                'expected' => null,
                'hide_from_catalogue' => 0,
                'id' => 152,
                'last_received' => '2020-11-09',
                'out_of_stock' => 0,
                'product_id' => 199,
                'status' => 'A',
            ],

            [
                'description' => 'DIVINE-PATCHOULI(ORGANIC) 100ML',
                'expected' => '2020-11-05',
                'hide_from_catalogue' => 0,
                'id' => 153,
                'last_received' => '2019-09-06',
                'out_of_stock' => 0,
                'product_id' => 141,
                'status' => 'A',
            ],

            [
                'description' => 'DIVINE-HAND SANITIZER-RAVINTSARA 60ML',
                'expected' => '2020-06-16',
                'hide_from_catalogue' => 0,
                'id' => 154,
                'last_received' => '2020-09-21',
                'out_of_stock' => 0,
                'product_id' => 17,
                'status' => 'A',
            ],

            [
                'description' => 'DIVINE-BL.PLASTIC BOTTLE 60ML+WHT SPRAY',
                'expected' => '2020-05-14',
                'hide_from_catalogue' => 0,
                'id' => 155,
                'last_received' => '2020-11-09',
                'out_of_stock' => 0,
                'product_id' => 52,
                'status' => 'A',
            ],

            [
                'description' => 'DIVINE-BL.PLASTIC BOTTLE 120ML+WHT SPRAY',
                'expected' => '2020-05-14',
                'hide_from_catalogue' => 0,
                'id' => 156,
                'last_received' => '2020-10-09',
                'out_of_stock' => 0,
                'product_id' => 51,
                'status' => 'A',
            ],

            [
                'description' => 'DIVINE-BL.GLASS ROLLON BOTTLE 15ML+SS',
                'expected' => '2020-07-08',
                'hide_from_catalogue' => 0,
                'id' => 157,
                'last_received' => '2020-10-28',
                'out_of_stock' => 0,
                'product_id' => 50,
                'status' => 'A',
            ],

            [
                'description' => 'DIVINE-BLUE GLASS JAR 60ML+WHITE LID',
                'expected' => '2020-06-25',
                'hide_from_catalogue' => 0,
                'id' => 158,
                'last_received' => '2020-07-31',
                'out_of_stock' => 0,
                'product_id' => 49,
                'status' => 'A',
            ],

            [
                'description' => 'DIVINE-BLUE GLASS JAR 30ML+WHITE LID',
                'expected' => null,
                'hide_from_catalogue' => 0,
                'id' => 159,
                'last_received' => '2020-11-12',
                'out_of_stock' => 0,
                'product_id' => 48,
                'status' => 'A',
            ],

            [
                'description' => 'DIVINE-BL.GLASS BOTTLE 100ML+WHT SPRAY',
                'expected' => '2020-06-01',
                'hide_from_catalogue' => 0,
                'id' => 160,
                'last_received' => '2020-11-09',
                'out_of_stock' => 0,
                'product_id' => 47,
                'status' => 'A',
            ],

            [
                'description' => 'DIVINE-BL.GLASS BOTTLE 1000ML+BLACK CAP',
                'expected' => null,
                'hide_from_catalogue' => 0,
                'id' => 161,
                'last_received' => '2020-11-10',
                'out_of_stock' => 0,
                'product_id' => 46,
                'status' => 'A',
            ],

            [
                'description' => 'DIVINE-BL.GLASS BOTTLE 50ML+WHT. SPRAY',
                'expected' => '2020-03-20',
                'hide_from_catalogue' => 0,
                'id' => 162,
                'last_received' => '2020-11-12',
                'out_of_stock' => 0,
                'product_id' => 45,
                'status' => 'A',
            ],

            [
                'description' => 'DIVINE-BL.GLASS BOTTLE 30ML+WHT. SPRAY',
                'expected' => '2020-06-25',
                'hide_from_catalogue' => 0,
                'id' => 163,
                'last_received' => '2020-10-19',
                'out_of_stock' => 0,
                'product_id' => 44,
                'status' => 'A',
            ],

            [
                'description' => 'DIVINE-BL.GLASS BOTTLE 30ML+GI.DROPPER',
                'expected' => '2020-10-06',
                'hide_from_catalogue' => 0,
                'id' => 164,
                'last_received' => '2020-10-21',
                'out_of_stock' => 0,
                'product_id' => 43,
                'status' => 'A',
            ],

            [
                'description' => 'DIVINE-BL.GLASS BOTTLE 30ML+BLACK CAP',
                'expected' => '2020-03-20',
                'hide_from_catalogue' => 0,
                'id' => 165,
                'last_received' => '2020-10-08',
                'out_of_stock' => 0,
                'product_id' => 42,
                'status' => 'A',
            ],

            [
                'description' => 'DIVINE-BL.GLASS BOTTLE 15ML+WHT. SPRAY',
                'expected' => '2020-11-04',
                'hide_from_catalogue' => 0,
                'id' => 166,
                'last_received' => '2020-11-02',
                'out_of_stock' => 0,
                'product_id' => 41,
                'status' => 'A',
            ],

            [
                'description' => 'DIVINE-BL.GLASS BOTTLE 15ML+GI.DROPPER',
                'expected' => '2020-06-25',
                'hide_from_catalogue' => 0,
                'id' => 167,
                'last_received' => '2020-11-09',
                'out_of_stock' => 0,
                'product_id' => 40,
                'status' => 'A',
            ],

            [
                'description' => 'DIVINE-BL.GLASS BOTTLE 15ML+BLACK CAP',
                'expected' => '2020-11-24',
                'hide_from_catalogue' => 0,
                'id' => 168,
                'last_received' => '2020-11-10',
                'out_of_stock' => 0,
                'product_id' => 39,
                'status' => 'A',
            ],

            [
                'description' => 'DIVINE-BL.GLASS BOTTLE 5ML+BLACK CAP',
                'expected' => '2020-10-05',
                'hide_from_catalogue' => 0,
                'id' => 169,
                'last_received' => '2020-10-20',
                'out_of_stock' => 0,
                'product_id' => 38,
                'status' => 'A',
            ],

            [
                'description' => '*ENJOY-DIPPED BANANA2X8X48G',
                'expected' => null,
                'hide_from_catalogue' => 0,
                'id' => 170,
                'last_received' => '2020-02-28',
                'out_of_stock' => 1,
                'product_id' => 153,
                'status' => 'D',
            ],

            [
                'description' => '*NJOY-DARK CHOCOLATE&RASPBERRY 8X48G',
                'expected' => null,
                'hide_from_catalogue' => 0,
                'id' => 171,
                'last_received' => '2020-01-21',
                'out_of_stock' => 1,
                'product_id' => 152,
                'status' => 'D',
            ],

            [
                'description' => '*ENJOY-BERRY MEDLEY6X250G',
                'expected' => '2019-10-22',
                'hide_from_catalogue' => 0,
                'id' => 172,
                'last_received' => '2020-03-12',
                'out_of_stock' => 1,
                'product_id' => 170,
                'status' => 'D',
            ],

            [
                'description' => '*ENJOY-FIG & MAPLEFLAVOUR 6X250G',
                'expected' => null,
                'hide_from_catalogue' => 0,
                'id' => 173,
                'last_received' => '2020-03-12',
                'out_of_stock' => 1,
                'product_id' => 169,
                'status' => 'D',
            ],

            [
                'description' => '*NJOY-CHOCOLATE CHIP& BANANA 6X250G',
                'expected' => '2020-03-27',
                'hide_from_catalogue' => 0,
                'id' => 174,
                'last_received' => '2020-02-26',
                'out_of_stock' => 1,
                'product_id' => 168,
                'status' => 'D',
            ],

            [
                'description' => '*NJOY-APPLE-CINNAMON6X250G',
                'expected' => '2020-03-28',
                'hide_from_catalogue' => 0,
                'id' => 175,
                'last_received' => '2020-03-12',
                'out_of_stock' => 1,
                'product_id' => 167,
                'status' => 'D',
            ],

            [
                'description' => '*ENJOY-MINI CONFECT.VARIETY EASTER12X179',
                'expected' => null,
                'hide_from_catalogue' => 0,
                'id' => 176,
                'last_received' => '2020-03-12',
                'out_of_stock' => 1,
                'product_id' => 171,
                'status' => 'D',
            ],

            [
                'description' => '*ENJOY-MINI COOKIESSHIPPER',
                'expected' => null,
                'hide_from_catalogue' => 0,
                'id' => 177,
                'last_received' => '0001-01-01',
                'out_of_stock' => 1,
                'product_id' => 172,
                'status' => 'D',
            ],

            [
                'description' => '*NJOY-BREAKFAST OVALS SHIPPER 36CT',
                'expected' => null,
                'hide_from_catalogue' => 0,
                'id' => 178,
                'last_received' => '0001-01-01',
                'out_of_stock' => 1,
                'product_id' => 166,
                'status' => 'D',
            ],

            [
                'description' => '**ENJOY-ENERGY BITESCLIP STRIP 12X180G',
                'expected' => null,
                'hide_from_catalogue' => 0,
                'id' => 179,
                'last_received' => '0001-01-01',
                'out_of_stock' => 1,
                'product_id' => 151,
                'status' => 'D',
            ],

            [
                'description' => '**ENJOY-BAKING MIXSHIPPER 1 UNIT',
                'expected' => null,
                'hide_from_catalogue' => 0,
                'id' => 180,
                'last_received' => '0001-01-01',
                'out_of_stock' => 1,
                'product_id' => 119,
                'status' => 'D',
            ],

            [
                'description' => 'HERBALAND-GUMMY 4 ADULTS:VEGAN COLLAGE90',
                'expected' => '2020-05-18',
                'hide_from_catalogue' => 0,
                'id' => 181,
                'last_received' => '2020-11-12',
                'out_of_stock' => 0,
                'product_id' => 150,
                'status' => 'A',
            ],

            [
                'description' => '**ERBALAND-HALLOWEENPROTEINGUMMIES40X10G',
                'expected' => '2020-10-27',
                'hide_from_catalogue' => 0,
                'id' => 182,
                'last_received' => '2020-10-23',
                'out_of_stock' => 0,
                'product_id' => 107,
                'status' => 'D',
            ],

            [
                'description' => 'HERBALAND-ELECTROLYTE GUMMIES 12X50G',
                'expected' => '2020-05-18',
                'hide_from_catalogue' => 0,
                'id' => 183,
                'last_received' => '2020-11-12',
                'out_of_stock' => 0,
                'product_id' => 73,
                'status' => 'A',
            ],

            [
                'description' => '**RBALAND-RAD RASPBERRY 12X50G',
                'expected' => '2020-03-20',
                'hide_from_catalogue' => 0,
                'id' => 184,
                'last_received' => '2020-04-24',
                'out_of_stock' => 0,
                'product_id' => 118,
                'status' => 'D',
            ],

            [
                'description' => 'HERBALAND-PEACH PASSION 12X50G',
                'expected' => '2020-01-11',
                'hide_from_catalogue' => 0,
                'id' => 185,
                'last_received' => '2020-10-27',
                'out_of_stock' => 0,
                'product_id' => 117,
                'status' => 'A',
            ],

            [
                'description' => 'HERBALAND-BLUEBERRYBURST 12X50G',
                'expected' => '2020-10-07',
                'hide_from_catalogue' => 0,
                'id' => 186,
                'last_received' => '2020-11-12',
                'out_of_stock' => 0,
                'product_id' => 116,
                'status' => 'A',
            ],

            [
                'description' => '**RBALAND-RED RASPBERRY-COMPOSTABLE12X50',
                'expected' => '2019-11-21',
                'hide_from_catalogue' => 0,
                'id' => 187,
                'last_received' => '2020-10-23',
                'out_of_stock' => 0,
                'product_id' => 76,
                'status' => 'D',
            ],

            [
                'description' => '**RBALAND-PEACH PASSION-COMPOSTABLE12X50',
                'expected' => '2019-11-21',
                'hide_from_catalogue' => 0,
                'id' => 188,
                'last_received' => '2020-10-23',
                'out_of_stock' => 0,
                'product_id' => 75,
                'status' => 'D',
            ],

            [
                'description' => '**ERBALAND-BLUEBERRYBURST-COMPOST 12X50G',
                'expected' => '2019-11-21',
                'hide_from_catalogue' => 0,
                'id' => 189,
                'last_received' => '2020-09-09',
                'out_of_stock' => 1,
                'product_id' => 74,
                'status' => 'D',
            ],

            [
                'description' => 'HERBALAND-TASTY TRIO20X13G',
                'expected' => '2020-11-27',
                'hide_from_catalogue' => 0,
                'id' => 190,
                'last_received' => '2020-10-13',
                'out_of_stock' => 0,
                'product_id' => 29,
                'status' => 'A',
            ],

            [
                'description' => 'LAND ART-MIGRAINE500  60 CAPS',
                'expected' => null,
                'hide_from_catalogue' => 0,
                'id' => 191,
                'last_received' => '2020-10-10',
                'out_of_stock' => 0,
                'product_id' => 72,
                'status' => 'A',
            ],

            [
                'description' => 'LAND ART-ALOE VERA GEL ORANGE-TANG 1500M',
                'expected' => '2020-02-08',
                'hide_from_catalogue' => 0,
                'id' => 192,
                'last_received' => '2020-11-12',
                'out_of_stock' => 0,
                'product_id' => 54,
                'status' => 'A',
            ],

            [
                'description' => 'LAND ART-ALOE VERATOPICAL GEL 100G',
                'expected' => null,
                'hide_from_catalogue' => 0,
                'id' => 193,
                'last_received' => '2020-11-09',
                'out_of_stock' => 0,
                'product_id' => 165,
                'status' => 'A',
            ],

            [
                'description' => 'LAND ART-ALOE VERA GEL ORANGE-TANG 500ML',
                'expected' => null,
                'hide_from_catalogue' => 0,
                'id' => 194,
                'last_received' => '2020-11-10',
                'out_of_stock' => 0,
                'product_id' => 53,
                'status' => 'A',
            ],

            [
                'description' => 'EO-EVERYONE SOAP KID-ORANGE SQUEEZE 946M',
                'expected' => '2020-04-23',
                'hide_from_catalogue' => 0,
                'id' => 195,
                'last_received' => '2020-07-17',
                'out_of_stock' => 0,
                'product_id' => 175,
                'status' => 'A',
            ],

            [
                'description' => 'EO-EVERYONE SOAP KID-TROP COCNT TWIST946',
                'expected' => '2019-11-28',
                'hide_from_catalogue' => 0,
                'id' => 196,
                'last_received' => '2020-07-03',
                'out_of_stock' => 0,
                'product_id' => 173,
                'status' => 'A',
            ],

            [
                'description' => 'EO-EVERYONE SOAP KID-LAV LULLABY 946ML',
                'expected' => '2019-12-03',
                'hide_from_catalogue' => 0,
                'id' => 197,
                'last_received' => '2020-07-01',
                'out_of_stock' => 0,
                'product_id' => 174,
                'status' => 'A',
            ],

            [
                'description' => '**O-EVERYONE 1/2 DRPSOAP&LOTION 73CT',
                'expected' => '2019-12-08',
                'hide_from_catalogue' => 1,
                'id' => 198,
                'last_received' => '2020-03-27',
                'out_of_stock' => 0,
                'product_id' => 142,
                'status' => 'D',
            ],

            [
                'description' => '**UKKA TEAS-FEEL NEW20TB',
                'expected' => '2020-04-08',
                'hide_from_catalogue' => 0,
                'id' => 199,
                'last_received' => '2020-05-14',
                'out_of_stock' => 1,
                'product_id' => 160,
                'status' => 'S',
            ],

            [
                'description' => '**KKA TEAS-TULSI CLARITY 20TB',
                'expected' => null,
                'hide_from_catalogue' => 0,
                'id' => 200,
                'last_received' => '2020-05-19',
                'out_of_stock' => 1,
                'product_id' => 159,
                'status' => 'S',
            ],
        ]);
    }
}
