<?php

namespace Database\Seeders\Development\iseed;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BrandsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('brands')->delete();

        DB::table('brands')->insert([

            [
                'allow_oi' => 0,
                'allows_amazon_resale' => 0,
                'also_distributed_by' => 'None currently',
                'category_code' => null,
                'brand_number' => '0111',
                'broker_proposal' => null,
                'business_partner_program' => 0,
                'catalogue_notice' => null,
                'catalogue_notice_fr' => null,
                'contract_exclusive' => 0,
                'created_at' => '2020-11-15 08:09:19',
                'currency_id' => 2,
                'deleted_at' => null,
                'description' => 'We are skin & hair wellness enthusiasts who believe in the power of purity to uplift the way you feel. We want to see every action you take lead to a stronger, healthier, more vibrant you that is ready to kick ass and take names.',
                'description_fr' => '',
                'health_first' => '1',
                'health_first_payment' => null,
                'health_first_payment_type' => null,
                'health_first_percentage' => null,
                'health_first_purity_percentage' => null,
                'hide_from_exports' => 0,
                'id' => 1,
                'in_house_brand' => 0,
                'made_in_canada' => 0,
                'map_pricing' => 0,
                'minimum_order_quantity' => 1000,
                'minimum_order_type' => '$',
                'name' => 'Acure',
                'name_fr' => 'Acure',
                'no_other_distributors' => 0,
                'nutrition_house' => '1',
                'nutrition_house_payment' => null,
                'nutrition_house_payment_type' => null,
                'nutrition_house_percentage' => null,
                'nutrition_house_purity_percentage' => null,
                'phone' => '(877) 902-2873',
                'product_availability' => 'Variable launch dates over the coming months. M2 will confirm.',
                'purchasing_specialist_id' => null,
                'shipping_lead_time' => '10',
                'state' => 1,
                'status' => 20,
                'unpublished_new_listing_deal' => '10% MCB on max 6 units',
                'unpublished_new_listing_deal_fr' => '10% MCB / maximum 6 unités',
                'updated_at' => '2020-11-15 08:09:19',
                'vendor_id' => 43,
                'vendor_relations_specialist_id' => null,
                'website' => 'acureorganics.com',
            ],

            [
                'allow_oi' => 0,
                'allows_amazon_resale' => 0,
                'also_distributed_by' => '',
                'category_code' => null,
                'brand_number' => '0131',
                'broker_proposal' => null,
                'business_partner_program' => 0,
                'catalogue_notice' => null,
                'catalogue_notice_fr' => null,
                'contract_exclusive' => 0,
                'created_at' => '2020-11-15 08:09:20',
                'currency_id' => 2,
                'deleted_at' => null,
                'description' => 'Andalou Naturals is the first Beauty Brand with all products Non-GMO Project verified. All of our vegetarian formulas are gluten-free and meet a minimum of 70% certified organic ingredient content, utilizing exceptional natural ingredients at effective levels for optimum results. Andalou Naturals shares your concern for animals, and without exception, we are cruelty-free and oppose all animal testing for cosmetic and personal care products.',
                'description_fr' => '',
                'health_first' => '',
                'health_first_payment' => null,
                'health_first_payment_type' => null,
                'health_first_percentage' => null,
                'health_first_purity_percentage' => null,
                'hide_from_exports' => 0,
                'id' => 2,
                'in_house_brand' => 0,
                'made_in_canada' => 0,
                'map_pricing' => 0,
                'minimum_order_quantity' => 1,
                'minimum_order_type' => '$',
                'name' => 'Andalou Naturals',
                'name_fr' => 'Andalou Naturals',
                'no_other_distributors' => 1,
                'nutrition_house' => '1',
                'nutrition_house_payment' => null,
                'nutrition_house_payment_type' => null,
                'nutrition_house_percentage' => null,
                'nutrition_house_purity_percentage' => null,
                'phone' => '415-446-9470',
                'product_availability' => '',
                'purchasing_specialist_id' => null,
                'shipping_lead_time' => '',
                'state' => 1,
                'status' => 20,
                'unpublished_new_listing_deal' => '15% = Up to 12 skus20% = 13 – 30 skus25% = 31+ skusMin = 2 PCs Per Sku. Max = 3 PCs Per SkuTravel Sizes Excluded. Natural Channel Only',
                'unpublished_new_listing_deal_fr' => '',
                'updated_at' => '2020-11-15 08:09:20',
                'vendor_id' => 4,
                'vendor_relations_specialist_id' => null,
                'website' => 'www.andalou.com',
            ],

            [
                'allow_oi' => 0,
                'allows_amazon_resale' => 0,
                'also_distributed_by' => 'Directa, Corwin, Indigo, Tree of Life, etc.',
                'category_code' => null,
                'brand_number' => '0137',
                'broker_proposal' => null,
                'business_partner_program' => 0,
                'catalogue_notice' => null,
                'catalogue_notice_fr' => null,
                'contract_exclusive' => 0,
                'created_at' => '2020-11-15 08:09:20',
                'currency_id' => 1,
                'deleted_at' => null,
                'description' => 'Eco friendly household cleaners, health and beauty products and baby products.',
                'description_fr' => 'Produits ménager, pour bébés et santé beauté Écologique.',
                'health_first' => '1',
                'health_first_payment' => null,
                'health_first_payment_type' => null,
                'health_first_percentage' => null,
                'health_first_purity_percentage' => null,
                'hide_from_exports' => 0,
                'id' => 3,
                'in_house_brand' => 0,
                'made_in_canada' => 1,
                'map_pricing' => 0,
                'minimum_order_quantity' => 2000,
                'minimum_order_type' => '$',
                'name' => 'Attitude',
                'name_fr' => 'Attitude',
                'no_other_distributors' => 0,
                'nutrition_house' => '1',
                'nutrition_house_payment' => null,
                'nutrition_house_payment_type' => null,
                'nutrition_house_percentage' => null,
                'nutrition_house_purity_percentage' => null,
                'phone' => '(514) 509-7225',
                'product_availability' => 'Always available',
                'purchasing_specialist_id' => null,
                'shipping_lead_time' => '10',
                'state' => 1,
                'status' => 20,
                'unpublished_new_listing_deal' => '15% MCB (max 6 units per SKU)',
                'unpublished_new_listing_deal_fr' => '15% MCB (max 6 unités par SKU)',
                'updated_at' => '2020-11-15 08:09:20',
                'vendor_id' => 64,
                'vendor_relations_specialist_id' => null,
                'website' => 'cleanattitude.com',
            ],

            [
                'allow_oi' => 0,
                'allows_amazon_resale' => 0,
                'also_distributed_by' => '',
                'category_code' => null,
                'brand_number' => '1120',
                'broker_proposal' => null,
                'business_partner_program' => 0,
                'catalogue_notice' => null,
                'catalogue_notice_fr' => null,
                'contract_exclusive' => 0,
                'created_at' => '2020-11-15 08:09:21',
                'currency_id' => 2,
                'deleted_at' => null,
                'description' => 'Bulletproof is an industry leader in coffee, nutrition and supplements developed to help people perform better, think faster, and live up to their fullest potential using a blend of time-tested knowledge and cutting-edge technology. Our supplements and foods are the purest available anywhere, and customers can expect to see an immediate difference in how they feel and perform. Environmentally conscious and ethically sourced products build a sustainable foundation for future generations to thrive. People worldwide are discovering the benefits of the Bulletproof Lifestyle. They’re losing weight, thinking faster, and feeling amazingly energized.',
                'description_fr' => '',
                'health_first' => '',
                'health_first_payment' => null,
                'health_first_payment_type' => null,
                'health_first_percentage' => null,
                'health_first_purity_percentage' => null,
                'hide_from_exports' => 0,
                'id' => 4,
                'in_house_brand' => 0,
                'made_in_canada' => 0,
                'map_pricing' => 0,
                'minimum_order_quantity' => 1,
                'minimum_order_type' => '$',
                'name' => 'Bulletproof',
                'name_fr' => '',
                'no_other_distributors' => 1,
                'nutrition_house' => '1',
                'nutrition_house_payment' => null,
                'nutrition_house_payment_type' => null,
                'nutrition_house_percentage' => null,
                'nutrition_house_purity_percentage' => null,
                'phone' => '(360) 775-2931',
                'product_availability' => 'TBD',
                'purchasing_specialist_id' => null,
                'shipping_lead_time' => '10',
                'state' => 1,
                'status' => 20,
                'unpublished_new_listing_deal' => '15% MCB (max. 6 units/SKU) on store\'s first time orders and Line extensions.',
                'unpublished_new_listing_deal_fr' => '15% de rabais ( maximum de 6 unités/SKU) sur toute première commande.',
                'updated_at' => '2020-11-15 08:09:21',
                'vendor_id' => 94,
                'vendor_relations_specialist_id' => null,
                'website' => 'bulletproof.com',
            ],

            [
                'allow_oi' => 0,
                'allows_amazon_resale' => 0,
                'also_distributed_by' => '',
                'category_code' => null,
                'brand_number' => '0313',
                'broker_proposal' => null,
                'business_partner_program' => 0,
                'catalogue_notice' => null,
                'catalogue_notice_fr' => null,
                'contract_exclusive' => 0,
                'created_at' => '2020-11-15 08:09:21',
                'currency_id' => 1,
                'deleted_at' => null,
                'description' => 'UNION NATURE Aroma-Phyto Inc. was founded in 1994. The company is a pioneer in the importation, manufacturing and distribution of aromatic products such as essential oils, floral waters and vegetable oils.',
                'description_fr' => 'UNION NATURE Aroma-Phyto inc. a été fondée en 1994. Elle fait figure d’entreprise québécoise pionnière dans le domaine de l’importation, fabrication et distribution de matières premières aromatiques telles que les huiles essentielles, les eaux florales et les huiles végétales certifiées biologiques par ECOCERT Canada.',
                'health_first' => '1',
                'health_first_payment' => null,
                'health_first_payment_type' => null,
                'health_first_percentage' => null,
                'health_first_purity_percentage' => null,
                'hide_from_exports' => 0,
                'id' => 5,
                'in_house_brand' => 0,
                'made_in_canada' => 1,
                'map_pricing' => 0,
                'minimum_order_quantity' => 1,
                'minimum_order_type' => '$',
                'name' => 'Divine Essence',
                'name_fr' => 'Divine Essence',
                'no_other_distributors' => 1,
                'nutrition_house' => '1',
                'nutrition_house_payment' => null,
                'nutrition_house_payment_type' => null,
                'nutrition_house_percentage' => null,
                'nutrition_house_purity_percentage' => null,
                'phone' => '(888) 344-9676',
                'product_availability' => 'February 15th',
                'purchasing_specialist_id' => null,
                'shipping_lead_time' => '10',
                'state' => 1,
                'status' => 20,
                'unpublished_new_listing_deal' => '15% MCB max 6 units per SKU',
                'unpublished_new_listing_deal_fr' => '15% MCB maximum de 6 unités par SKU',
                'updated_at' => '2020-11-15 08:09:21',
                'vendor_id' => 122,
                'vendor_relations_specialist_id' => null,
                'website' => 'union-nature.com',
            ],

            [
                'allow_oi' => 0,
                'allows_amazon_resale' => 0,
                'also_distributed_by' => 'ONFC, Horizon, UNFI, PSC, Coop D\'Alentour',
                'category_code' => null,
                'brand_number' => '0332',
                'broker_proposal' => null,
                'business_partner_program' => 0,
                'catalogue_notice' => null,
                'catalogue_notice_fr' => null,
                'contract_exclusive' => 0,
                'created_at' => '2020-11-15 08:09:21',
                'currency_id' => 1,
                'deleted_at' => null,
                'description' => 'Enjoy Life is the delicious “Free From” brand committed to food health that deeply understands and empathizes with nutritional standard challengers’ passionate Interest in how food is made and the benefits it can deliver.',
                'description_fr' => '',
                'health_first' => '',
                'health_first_payment' => null,
                'health_first_payment_type' => null,
                'health_first_percentage' => null,
                'health_first_purity_percentage' => null,
                'hide_from_exports' => 0,
                'id' => 6,
                'in_house_brand' => 0,
                'made_in_canada' => 0,
                'map_pricing' => 0,
                'minimum_order_quantity' => 5000,
                'minimum_order_type' => '$',
                'name' => 'Enjoy Life Foods',
                'name_fr' => 'Enjoy Life Foods',
                'no_other_distributors' => 0,
                'nutrition_house' => '1',
                'nutrition_house_payment' => null,
                'nutrition_house_payment_type' => null,
                'nutrition_house_percentage' => null,
                'nutrition_house_purity_percentage' => null,
                'phone' => '(888) 503-6569',
                'product_availability' => '01-Aug-17',
                'purchasing_specialist_id' => null,
                'shipping_lead_time' => '10',
                'state' => 1,
                'status' => 20,
                'unpublished_new_listing_deal' => 'New store deals, Top account discounts please contact Courtney (Courtney Stone cstone@marsham.ca) and Franco (Franco Vieni  fvieni@enjoylifefoods.com)',
                'unpublished_new_listing_deal_fr' => '',
                'updated_at' => '2020-11-15 08:09:21',
                'vendor_id' => 147,
                'vendor_relations_specialist_id' => null,
                'website' => 'www.enjoylifefoods.ca',
            ],

            [
                'allow_oi' => 0,
                'allows_amazon_resale' => 0,
                'also_distributed_by' => '',
                'category_code' => null,
                'brand_number' => '0565',
                'broker_proposal' => null,
                'business_partner_program' => 0,
                'catalogue_notice' => null,
                'catalogue_notice_fr' => null,
                'contract_exclusive' => 0,
                'created_at' => '2020-11-15 08:09:21',
                'currency_id' => 2,
                'deleted_at' => null,
                'description' => 'Everyone Brand, is manufactured by Small World Trading Co.  A family owned manufacturer of body and face care products based on the traditional healing and therapeutic wisdom of essential oils.',
                'description_fr' => '',
                'health_first' => '',
                'health_first_payment' => null,
                'health_first_payment_type' => null,
                'health_first_percentage' => null,
                'health_first_purity_percentage' => null,
                'hide_from_exports' => 0,
                'id' => 7,
                'in_house_brand' => 0,
                'made_in_canada' => 0,
                'map_pricing' => 0,
                'minimum_order_quantity' => 1,
                'minimum_order_type' => '$',
                'name' => 'Everyone',
                'name_fr' => '',
                'no_other_distributors' => 1,
                'nutrition_house' => '1',
                'nutrition_house_payment' => null,
                'nutrition_house_payment_type' => null,
                'nutrition_house_percentage' => null,
                'nutrition_house_purity_percentage' => null,
                'phone' => '800-570-3775',
                'product_availability' => '',
                'purchasing_specialist_id' => null,
                'shipping_lead_time' => '',
                'state' => 1,
                'status' => 20,
                'unpublished_new_listing_deal' => 'Buy 2, Get 2 FreeorBuy 3, Get 3 Free',
                'unpublished_new_listing_deal_fr' => '',
                'updated_at' => '2020-11-15 08:09:21',
                'vendor_id' => 12,
                'vendor_relations_specialist_id' => null,
                'website' => 'www.eoproducts.com',
            ],

            [
                'allow_oi' => 0,
                'allows_amazon_resale' => 0,
                'also_distributed_by' => 'Christmas Naturals',
                'category_code' => null,
                'brand_number' => '0459',
                'broker_proposal' => null,
                'business_partner_program' => 0,
                'catalogue_notice' => null,
                'catalogue_notice_fr' => null,
                'contract_exclusive' => 0,
                'created_at' => '2020-11-15 08:09:21',
                'currency_id' => 1,
                'deleted_at' => null,
                'description' => 'Herbaland Naturals is Canada’s leading manufacturer of enhanced confectionery delivery systems for the nutraceutical market.  We produce gummy vitamins and supplements with a delicious recipe using the highest quality raw materials available, manufactured at our own local facility, free of artificial additives & preservatives.',
                'description_fr' => 'Herbaland Naturals est le premier fabricant de systèmes améliorés de distribution de confiserie pour le marché nutraceutique au Canada. Nous produisons des vitamines et des suppléments gommeux avec une délicieuse recette en utilisant la plus haute qualité des matières premières disponibles, fabriqués dans notre propre usine locale, exempte d\'additifs et de conservateurs artificiels.',
                'health_first' => '1',
                'health_first_payment' => null,
                'health_first_payment_type' => null,
                'health_first_percentage' => null,
                'health_first_purity_percentage' => null,
                'hide_from_exports' => 0,
                'id' => 8,
                'in_house_brand' => 0,
                'made_in_canada' => 1,
                'map_pricing' => 0,
                'minimum_order_quantity' => 1000,
                'minimum_order_type' => '$',
                'name' => 'Herbaland',
                'name_fr' => 'Herbaland',
                'no_other_distributors' => 0,
                'nutrition_house' => '1',
                'nutrition_house_payment' => null,
                'nutrition_house_payment_type' => null,
                'nutrition_house_percentage' => null,
                'nutrition_house_purity_percentage' => null,
                'phone' => '(888) 223-2140',
                'product_availability' => '11/23/2015',
                'purchasing_specialist_id' => null,
                'shipping_lead_time' => '30',
                'state' => 1,
                'status' => 20,
                'unpublished_new_listing_deal' => 'Bottled products: Buy 3 get 1Carton/pouch products:2 cartons (10% MCB)  4 cartons (15% MCB) 6 cartons (20% MCB)Suggested SKUs:Protein Gummies: Fantastic Fruit  (50g)Protein Gummies: Wild Berry (50g)Protein Gummies: Kiwi & Friends (50g)Good News Gummies: Blueberry BurstGood News Gummies: Peach PassionGood News Gummies: Rad Raspberry',
                'unpublished_new_listing_deal_fr' => '',
                'updated_at' => '2020-11-15 08:09:21',
                'vendor_id' => 196,
                'vendor_relations_specialist_id' => null,
                'website' => 'www.herbaland.ca/',
            ],

            [
                'allow_oi' => 0,
                'allows_amazon_resale' => 0,
                'also_distributed_by' => 'Puresource',
                'category_code' => null,
                'brand_number' => '0506',
                'broker_proposal' => null,
                'business_partner_program' => 0,
                'catalogue_notice' => null,
                'catalogue_notice_fr' => null,
                'contract_exclusive' => 0,
                'created_at' => '2020-11-15 08:09:21',
                'currency_id' => 1,
                'deleted_at' => null,
                'description' => 'Developed and manufactured in Canada, Land Art products are high quality liquid dietary supplements. All products are made from the best ingredients, are gluten free and contains no artificial flavouring, coloring or sweeteners.',
                'description_fr' => 'Conçus et fabriqués au Canada, les produits liquides de la marque Land Art sont de qualité supérieure. Tous les produits sont composés d',
                'health_first' => '1',
                'health_first_payment' => null,
                'health_first_payment_type' => null,
                'health_first_percentage' => null,
                'health_first_purity_percentage' => null,
                'hide_from_exports' => 0,
                'id' => 9,
                'in_house_brand' => 0,
                'made_in_canada' => 1,
                'map_pricing' => 0,
                'minimum_order_quantity' => 1,
                'minimum_order_type' => '$',
                'name' => 'Land Art',
                'name_fr' => 'Land Art',
                'no_other_distributors' => 0,
                'nutrition_house' => '',
                'nutrition_house_payment' => null,
                'nutrition_house_payment_type' => null,
                'nutrition_house_percentage' => null,
                'nutrition_house_purity_percentage' => null,
                'phone' => '(800) 445-0441',
                'product_availability' => 'JUNE 1ST',
                'purchasing_specialist_id' => null,
                'shipping_lead_time' => '5',
                'state' => 1,
                'status' => 20,
                'unpublished_new_listing_deal' => '',
                'unpublished_new_listing_deal_fr' => '',
                'updated_at' => '2020-11-15 08:09:21',
                'vendor_id' => 215,
                'vendor_relations_specialist_id' => null,
                'website' => 'www.landart.ca',
            ],

            [
                'allow_oi' => 0,
                'allows_amazon_resale' => 0,
                'also_distributed_by' => '',
                'category_code' => null,
                'brand_number' => '0690B',
                'broker_proposal' => null,
                'business_partner_program' => 0,
                'catalogue_notice' => null,
                'catalogue_notice_fr' => null,
                'contract_exclusive' => 0,
                'created_at' => '2020-11-15 08:09:21',
                'currency_id' => 1,
                'deleted_at' => null,
                'description' => 'Incredible organic teas and food supplements that combine nature’s finest ethically sourced herbs with the wisdom of our master herbsmith Sebastian Pole.   Together we create uniquely beautiful, beneficial blends.',
                'description_fr' => '',
                'health_first' => '',
                'health_first_payment' => null,
                'health_first_payment_type' => null,
                'health_first_percentage' => null,
                'health_first_purity_percentage' => null,
                'hide_from_exports' => 0,
                'id' => 10,
                'in_house_brand' => 0,
                'made_in_canada' => 0,
                'map_pricing' => 0,
                'minimum_order_quantity' => 1,
                'minimum_order_type' => '$',
                'name' => 'Pukka Tea',
                'name_fr' => '',
                'no_other_distributors' => 1,
                'nutrition_house' => '',
                'nutrition_house_payment' => null,
                'nutrition_house_payment_type' => null,
                'nutrition_house_percentage' => null,
                'nutrition_house_purity_percentage' => null,
                'phone' => '',
                'product_availability' => '',
                'purchasing_specialist_id' => null,
                'shipping_lead_time' => '',
                'state' => 1,
                'status' => 20,
                'unpublished_new_listing_deal' => '20% off opening order (pukka only)Minimum 10 cases/40 units (pukka)',
                'unpublished_new_listing_deal_fr' => '20% off opening order (pukka only)Minimum 10 cases (pukka)',
                'updated_at' => '2020-11-15 08:09:21',
                'vendor_id' => 1,
                'vendor_relations_specialist_id' => null,
                'website' => '',
            ],
        ]);
    }
}
