<?php

namespace Database\Seeders\Development\iseed;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ContactsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('contacts')->delete();

        DB::table('contacts')->insert([

            [
                'cloned_from_id' => null,
                'contactable_id' => 1,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'brentpallett@bulkbarn.ca',
                'name' => 'Brent Pallett',
                'phone' => '905-726-5000 ext. 8340',
                'position' => null,
                'role' => 'Buyer',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 1,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'LaceyCarter@bulkbarn.ca',
                'name' => 'Lacey Carter',
                'phone' => '905-726-5000 ext. 8352',
                'position' => null,
                'role' => 'Buyer',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 4,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => '',
                'name' => 'ANNE PILON',
                'phone' => '',
                'position' => null,
                'role' => 'Buyer',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 4,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => '',
                'name' => 'KIM KLAUSEN',
                'phone' => '',
                'position' => null,
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 6,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'franca.contardo@loblaw.ca',
                'name' => 'Franca Contardo',
                'phone' => '905.459.2500 ext 616571',
                'position' => 'Cough/Smoke/Eyes',
                'role' => 'Buyer',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 6,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'steven.bernard@loblaw.ca',
                'name' => 'Steve Bernard',
                'phone' => '905.459.2500 ext 6728',
                'position' => 'Diet/Multi Vitamins',
                'role' => 'Buyer',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 6,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'slavika.kacaverik@loblaw.ca',
                'name' => 'Slavika Kacaverik',
                'phone' => '905.459.2500',
                'position' => 'Oral Care',
                'role' => 'Buyer',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 6,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'Adwin.simpson@loblaw.ca',
                'name' => 'Adwin Simpson',
                'phone' => '',
                'position' => 'Steve Bernard assistant',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 6,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'cheryl.sultana@loblaw.ca',
                'name' => 'Cheryl Sultana',
                'phone' => '',
                'position' => 'Franca assistant',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 7,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'Jill.Rudderham@loblaw.ca',
                'name' => 'Aaron Skelton',
                'phone' => '905.459.2500 ext 616294',
                'position' => 'Food',
                'role' => 'Buyer',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 7,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'shaun.kernaghan@loblaw.ca',
                'name' => 'Shaun Kernaghan',
                'phone' => '905.459.2500 ext 616294',
                'position' => 'Supplements/NPC',
                'role' => 'Buyer',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 7,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'brenda.fontes@loblaw.ca',
                'name' => 'Brenda Fontes',
                'phone' => '905.383.5445 ext 3232',
                'position' => 'Senior Merchandising Manager Fortinos',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 7,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'laura.usher@loblaw.ca',
                'name' => 'Laura Usher',
                'phone' => '905.459.2500 ext 616955',
                'position' => 'Merchant',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 7,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => '',
                'name' => 'Izabella Shaker',
                'phone' => '',
                'position' => 'Associate Merchant',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 7,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'francisca.noegroho@loblaw.ca',
                'name' => 'Francisca Noegroho',
                'phone' => '905.459.2500 ext 616688',
                'position' => 'Associate Merchant',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 7,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'sharon.rice@loblaw.ca',
                'name' => 'Sharon Rice',
                'phone' => '905.459.2500 ext 615938',
                'position' => 'Assistant Category Manager',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 7,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => '',
                'name' => 'Elizabeth Crawley',
                'phone' => '905-459-2500 ext 615631',
                'position' => 'Director - Natural Value',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 12,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'CFiorino@shoppersdrugmart.ca',
                'name' => 'Cecilia Fiorino',
                'phone' => '(416) 490-2649',
                'position' => 'Hair Care',
                'role' => 'Buyer',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 12,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'LEllis@shoppersdrugmart.ca',
                'name' => 'Lian Ellis',
                'phone' => '(416) 490-2706',
                'position' => 'NHP/ Cough & Cold/Fem Care',
                'role' => 'Buyer',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 12,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'kholmes@shoppersdrugmart.ca',
                'name' => 'Kelly Holmes',
                'phone' => '(416) 490-2799',
                'position' => 'Oral Care',
                'role' => 'Buyer',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 12,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'Smulvihill@shoppersdrugmart.ca',
                'name' => 'Steve Mulvihill',
                'phone' => '(416) 490-2659',
                'position' => 'Skin Care',
                'role' => 'Buyer',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 12,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'KeSmith@shoppersdrugmart.ca',
                'name' => 'Kevin Smith',
                'phone' => '416 493-1220 ext 5702',
                'position' => 'Category Ass\'t-Oral Care',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 12,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'achora@shoppersdrugmart.ca',
                'name' => 'Anna Chora',
                'phone' => '(416) 493-1220 ext.5537',
                'position' => 'Category Ass\'t - Vitamins',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 12,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'JOlee@shoppersdrugmart.ca',
                'name' => 'Jonathan Lee',
                'phone' => '(416) 493-1220 ex 5286',
                'position' => 'Category Ass\'t-NHP/C&C/Fem Care',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 12,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'LFleetwood@shoppersdrugmart.ca',
                'name' => 'Laurie Fleetwood',
                'phone' => '(416) 493-1220 ext 5392',
                'position' => 'Category Ass\'t - Skin Care',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 12,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'Hnoori@shoppersdrugmart.ca',
                'name' => 'Haroon Noori',
                'phone' => '(416) 493-1220 ext 5639',
                'position' => 'Manager Inventory Management',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 12,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'Jstamper@shoppersdrugmart.ca',
                'name' => 'Jacqueline Stamper',
                'phone' => '(416) 493-1220 ext 3071',
                'position' => 'Buyer',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 12,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => '',
                'name' => 'John Georgiadis',
                'phone' => '(416) 493-1220',
                'position' => 'Director Category Mgmt-OTC',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 12,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => '',
                'name' => 'Kelly Jessop',
                'phone' => '(416) 493-1220',
                'position' => 'Director Category Mgmt-HBA',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 12,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => '',
                'name' => 'Sue Donaldson',
                'phone' => '',
                'position' => 'Manager-Analytics',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 13,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'lily.fernandes@shopatshowcase.com',
                'name' => 'Lily Fernandes',
                'phone' => '905-452-0392 x260',
                'position' => null,
                'role' => 'Buyer',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 16,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'bskokandich@vitaminshoppe.com',
                'name' => 'Bryan Skokandich',
                'phone' => '201.624.3061',
                'position' => 'associate category manager Canada',
                'role' => 'Buyer',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 16,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'michelle.mejia@vitaminshoppe.com',
                'name' => 'Michelle Mejia',
                'phone' => '201.624.3283',
                'position' => 'category manager',
                'role' => 'Buyer',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 17,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'brad.eltherington@wal-mart.com',
                'name' => 'Brad Eltherington',
                'phone' => '905-821-2111 x',
                'position' => 'D40 Vitamins / Teas',
                'role' => 'Buyer',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 17,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'grant.hennig@wal-mart.com',
                'name' => 'Grant Hennig',
                'phone' => '905-821-2111 ext 4005',
                'position' => 'D40 Natural HBA',
                'role' => 'Buyer',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 17,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'Caroline.Pius@wal-mart.com',
                'name' => 'Caroline Pius',
                'phone' => '(905) 821-2111 x4417',
                'position' => 'D46 Specialty Bath',
                'role' => 'Buyer',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 17,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'julius.fernandes@wal-mart.com',
                'name' => 'Julius Fernandes',
                'phone' => '905-821-2111 x',
                'position' => 'Body / Fem. Hygiene / Oral Care',
                'role' => 'Buyer',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 17,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'dwallac@wal-mart.com',
                'name' => 'Diane Wallace',
                'phone' => '905-821-2111 x',
                'position' => 'Hair Care',
                'role' => 'Buyer',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 17,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'tanya.spencer@wal-mart.com',
                'name' => 'Tanya Spencer',
                'phone' => '905-821-2111 x',
                'position' => 'Skin Care',
                'role' => 'Buyer',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 17,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'Mark.Hilton@wal-mart.com',
                'name' => 'Mark Hilton',
                'phone' => '905-821-2111 ext 8396',
                'position' => 'DMM',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 17,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'Nazeema.Mohabir@wal-mart.com',
                'name' => 'Nazeema Mohabir',
                'phone' => '905-821-2111 ext 8394',
                'position' => 'Pharmacy Merchandise Assistant',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 17,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'Jessica.Pacheco@wal-mart.com',
                'name' => 'Jessica Pacheco',
                'phone' => '(905) 821-2111 ext. 4047',
                'position' => 'Category Team Analyst',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 19,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'Rob.Luscombe@wholefoods.com',
                'name' => 'Rob Luscombe',
                'phone' => '(905) 273-0192',
                'position' => 'Grocery Buyer',
                'role' => 'Buyer',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 19,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'andrew.mara-mckay@wholefoods.com',
                'name' => 'Drew Mara-McKay',
                'phone' => '(905) 273-0193',
                'position' => 'Whole Body Buyer',
                'role' => 'Buyer',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 19,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'gary.macdonald@wholefoods.com',
                'name' => 'Gary MacDonald',
                'phone' => '905.273.0191',
                'position' => 'Purchasing Coordinator',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 19,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'MW.ONT.GRO.WB.CATEGORY.REVIEW@wholefoods.com',
                'name' => ' ',
                'phone' => '',
                'position' => 'Category Review Submissions',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 19,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'Beth.Eckerty@wholefoods.com',
                'name' => 'Beth Eckerty',
                'phone' => '312.799.5623',
                'position' => 'MW Whole Body Coordinator',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 20,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'mary.frewen@wholefoods.com',
                'name' => 'Mary Frewen',
                'phone' => '236-521-2707',
                'position' => 'Whole Body',
                'role' => 'Buyer',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 20,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'Richard.Williams@wholefoods.com',
                'name' => 'Richard Williams',
                'phone' => '236-521-2706',
                'position' => 'Grocery',
                'role' => 'Buyer',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 20,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'Suzanne.Geohagan@wholefoods.com',
                'name' => 'Suzanne Geohagan',
                'phone' => '',
                'position' => 'Whole Body Coordinator',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 20,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'Elaine.Arrowsmith@wholefoods.com',
                'name' => 'Elaine Arrowsmith',
                'phone' => '236.521.2705',
                'position' => 'Pacific Northwest region',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 20,
                'contactable_type' => 'App\\Models\\Retailer',
                'created_at' => '2020-08-19 11:30:38',
                'deleted_at' => null,
                'email' => 'Bruce.Cancilla@wholefoods.com',
                'name' => 'Bruce Cancilla',
                'phone' => '',
                'position' => 'Purchasing Coordinator Western Canada',
                'role' => 'Other',
                'updated_at' => '2020-08-19 11:30:38',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 43,
                'contactable_type' => 'App\\Models\\Vendor',
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'email' => 'dustin@acureorganics.com',
                'name' => 'Dustin Fauth',
                'phone' => '(877) 902-2873',
                'position' => 'General Manager',
                'role' => 'vendor',
                'updated_at' => '2020-11-15 08:09:37',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 43,
                'contactable_type' => 'App\\Models\\Vendor',
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'email' => 'catherine@msquaredbrands.com',
                'name' => 'Catherine Vaillant',
                'phone' => '(514) 989-8156',
                'position' => 'Broker-M2',
                'role' => 'vendorlink',
                'updated_at' => '2020-11-15 08:09:37',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 43,
                'contactable_type' => 'App\\Models\\Vendor',
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'email' => 'receivables@acureorganics.com',
                'name' => 'Receivables department ',
                'phone' => '(877) 902-2873',
                'position' => 'Various employees',
                'role' => 'Payment',
                'updated_at' => '2020-11-15 08:09:37',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 64,
                'contactable_type' => 'App\\Models\\Vendor',
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'email' => 'mlusignan@bio-spectra.com',
                'name' => 'Mélissa Lusignan',
                'phone' => '514-509-7225 ext 229',
                'position' => 'Sales Manager',
                'role' => 'vendor',
                'updated_at' => '2020-11-15 08:09:37',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 64,
                'contactable_type' => 'App\\Models\\Vendor',
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'email' => 'eromero@bio-spectra.com',
                'name' => 'Emilexy Romero',
                'phone' => '(514) 509-7225',
                'position' => 'Finance Manager',
                'role' => 'Payment',
                'updated_at' => '2020-11-15 08:09:37',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 94,
                'contactable_type' => 'App\\Models\\Vendor',
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'email' => 'lindsay@bulletproof.com',
                'name' => 'Lindsay Myron',
                'phone' => '(360) 775-2931',
                'position' => 'Business Development Manager',
                'role' => 'vendor',
                'updated_at' => '2020-11-15 08:09:37',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 94,
                'contactable_type' => 'App\\Models\\Vendor',
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'email' => 'susan.ro@bulletproof.com',
                'name' => 'Susan Ro',
                'phone' => '(425) 772-4588',
                'position' => 'Staff Accountant',
                'role' => 'Payment',
                'updated_at' => '2020-11-15 08:09:37',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 122,
                'contactable_type' => 'App\\Models\\Vendor',
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'email' => 'cedrick.w.robert@union-nature.com',
                'name' => 'Cedrick W. Robert',
                'phone' => '(514) 344-7777',
                'position' => 'Marketing',
                'role' => 'vendor',
                'updated_at' => '2020-11-15 08:09:37',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 122,
                'contactable_type' => 'App\\Models\\Vendor',
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'email' => 'admin@union-nature.com',
                'name' => 'Annie Ratté',
                'phone' => '(514) 344-7777',
                'position' => 'Accounting',
                'role' => 'Payment',
                'updated_at' => '2020-11-15 08:09:37',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 147,
                'contactable_type' => 'App\\Models\\Vendor',
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'email' => 'fvieni@enjoylifefoods.com',
                'name' => 'Franco Vieni',
                'phone' => '(416) 303-5241',
                'position' => 'Region Manager',
                'role' => 'vendor',
                'updated_at' => '2020-11-15 08:09:37',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 147,
                'contactable_type' => 'App\\Models\\Vendor',
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'email' => 'cdevore@enjoylifefoods.com',
                'name' => 'Christomer Devore',
                'phone' => '(888) 503-6569',
                'position' => 'Food & Safety Manager',
                'role' => 'QC',
                'updated_at' => '2020-11-15 08:09:37',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 196,
                'contactable_type' => 'App\\Models\\Vendor',
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'email' => 'john@herbaland.ca',
                'name' => 'John Bentley',
                'phone' => '(604) 284-5050',
                'position' => 'Account Manager, NA',
                'role' => 'vendor',
                'updated_at' => '2020-11-15 08:09:37',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 196,
                'contactable_type' => 'App\\Models\\Vendor',
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'email' => 'john@herbaland.ca',
                'name' => 'John Bentley',
                'phone' => '(604) 284-5050',
                'position' => 'Account Manager, NA',
                'role' => 'vendorlink',
                'updated_at' => '2020-11-15 08:09:37',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 196,
                'contactable_type' => 'App\\Models\\Vendor',
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'email' => 'john@herbaland.ca',
                'name' => 'John Bentley',
                'phone' => '(604) 284-5050',
                'position' => 'Account Manager, NA',
                'role' => 'Purchasing',
                'updated_at' => '2020-11-15 08:09:37',
            ],

            [
                'cloned_from_id' => null,
                'contactable_id' => 215,
                'contactable_type' => 'App\\Models\\Vendor',
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'email' => 'nmartineau@aromatik.ca',
                'name' => 'Nicolas Martineau',
                'phone' => '450-929-1933, ext 227',
                'position' => 'Key Accounts Director',
                'role' => 'vendor',
                'updated_at' => '2020-11-15 08:09:37',
            ],
        ]);
    }
}
