<?php

namespace Database\Seeders\Development\iseed;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VendorsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('vendors')->delete();

        DB::table('vendors')->insert([

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 1,
                'name' => 'Advantage Health Matters',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 2,
                'name' => 'All things Jill',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 3,
                'name' => 'ANB',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 4,
                'name' => 'Andalou',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 5,
                'name' => 'Atrium/Trophic',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 6,
                'name' => 'Au Naturel',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 7,
                'name' => 'Avaria',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 8,
                'name' => 'CanPrev',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 9,
                'name' => 'Carina Organics',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 10,
                'name' => 'Chorus Supernaturals',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 11,
                'name' => 'East West Science',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 12,
                'name' => 'EO Products',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 13,
                'name' => 'Every Man Jack',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 14,
                'name' => 'Fresh Wave',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 15,
                'name' => 'Frontier Group',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 16,
                'name' => 'Genuine Tea',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 17,
                'name' => 'Hain',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 18,
                'name' => 'Homeocan',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 19,
                'name' => 'Hush Brands',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 20,
                'name' => 'KMH Touches',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 21,
                'name' => 'KOA Naturals',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 22,
                'name' => 'Lee\'s Provisions',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 23,
                'name' => 'M.C.P. McCaughey Consumer Products Management Inc',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 24,
                'name' => 'Made Good',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 25,
                'name' => 'Natural Health Distribution',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 26,
                'name' => 'Nutrition Excellence',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 27,
                'name' => 'RX Balance',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 28,
                'name' => 'Think Operations',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 29,
                'name' => 'True Naturals',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 30,
                'name' => 'Unilever',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 31,
                'name' => 'Vivo',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 32,
                'name' => 'wellnx',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 33,
                'name' => '0386 Formula Corp',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 34,
                'name' => 'Farley Co',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 35,
                'name' => 'Aurium',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 36,
                'name' => 'Platinum Naturals',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => null,
                'cheque_payable_to' => null,
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => true,
                'id' => 37,
                'name' => 'TOP Nutritionals',
                'payment_terms' => null,
                'phone' => null,
                'return_policy' => null,
                'special_shipping_requirements' => null,
                'state' => 0,
                'status' => 10,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => null,
            ],

            [
                'backorder_policy' => '',
                'cheque_payable_to' => 'Better Planet Brands',
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => 1,
                'id' => 43,
                'name' => 'Acure',
                'payment_terms' => '2% 15 / NET 30',
                'phone' => '(877) 902-2873',
                'return_policy' => '',
                'special_shipping_requirements' => '',
                'state' => 1,
                'status' => 20,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => 'Acure',
            ],

            [
                'backorder_policy' => '',
                'cheque_payable_to' => 'Bio-Spectra',
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => 1,
                'id' => 64,
                'name' => 'Attitude',
                'payment_terms' => '2% 10 / NET 30',
                'phone' => '(514) 509-7225',
                'return_policy' => '',
                'special_shipping_requirements' => '',
                'state' => 1,
                'status' => 20,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => 'Attitude',
            ],

            [
                'backorder_policy' => '',
                'cheque_payable_to' => 'Bulletproof Digital, Inc.',
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => 1,
                'id' => 94,
                'name' => 'Bulletproof',
                'payment_terms' => 'NET 30',
                'phone' => '(360) 775-2931',
                'return_policy' => '',
                'special_shipping_requirements' => '',
                'state' => 1,
                'status' => 20,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => 'Bulletproof',
            ],

            [
                'backorder_policy' => '',
                'cheque_payable_to' => 'Union-Nature',
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => 1,
                'id' => 122,
                'name' => 'Divine Essence',
                'payment_terms' => '2% 10 / NET 30',
                'phone' => '(888) 344-9676',
                'return_policy' => '',
                'special_shipping_requirements' => '',
                'state' => 1,
                'status' => 20,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => 'Divine Essence',
            ],

            [
                'backorder_policy' => '',
                'cheque_payable_to' => 'Enjoy Life Foods',
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => 0,
                'id' => 147,
                'name' => 'Enjoy Life Foods',
                'payment_terms' => 'NET 30',
                'phone' => '(888) 503-6569',
                'return_policy' => '',
                'special_shipping_requirements' => '',
                'state' => 1,
                'status' => 20,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => '',
            ],

            [
                'backorder_policy' => '',
                'cheque_payable_to' => 'Herbaland Naturals Inc.',
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => 1,
                'id' => 196,
                'name' => 'Herbaland',
                'payment_terms' => '2% 15 / NET 45',
                'phone' => '(888) 223-2140',
                'return_policy' => '',
                'special_shipping_requirements' => '',
                'state' => 1,
                'status' => 20,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => 'Herbaland',
            ],

            [
                'backorder_policy' => 'All BO cancelled',
                'cheque_payable_to' => 'Supplements Aromatik inc.',
                'created_at' => '2020-11-15 08:09:37',
                'deleted_at' => null,
                'fob_purity_distribution_centres' => 1,
                'id' => 215,
                'name' => 'Land Art',
                'payment_terms' => '1% 15 / NET 30',
                'phone' => '(800) 445-0441',
                'return_policy' => 'No returns',
                'special_shipping_requirements' => '',
                'state' => 1,
                'status' => 20,
                'updated_at' => '2020-11-15 08:09:37',
                'who_to_mcb' => 'Land Art',
            ],
        ]);
    }
}
