name: Laravel CI

on:
  [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: plic
          MYSQL_USER: user
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secretroot
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=2s --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Create Kyolic test database
        run: mysql --host 127.0.0.1 --port 3307 -uroot -psecretroot -e 'CREATE DATABASE IF NOT EXISTS kyolic;'

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install NPM packages
        run: npm ci

      - name: Build frontend
        run: npm run development

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Create Directories
        run: mkdir -p bootstrap/cache storage/framework/cache storage/framework/sessions storage/framework/views storage/app

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Generate key
        env:
            MYSQL_DATABASE: plic
            DB_USERNAME: root
            DB_PASSWORD: secretroot
            DB_PORT: 3307
        run: php artisan key:generate

      - name: Migrate and seed database
        env:
            MYSQL_DATABASE: plic
            DB_USERNAME: root
            DB_PASSWORD: secretroot
            DB_PORT: 3307
        run: php artisan migrate:fresh --seed --env=testing

      - name: Link storage folder
        env:
            MYSQL_DATABASE: plic
            DB_USERNAME: root
            DB_PASSWORD: secretroot
            DB_PORT: 3307
        run: php artisan storage:link

      - name: Execute tests via Pest
        env:
          DEBUGBAR_ENABLED: false
          MYSQL_DATABASE: plic
          DB_USERNAME: root
          DB_PASSWORD: secretroot
          DB_PORT: 3307
          KYOLIC_DB_CONNECTION: mysql
          KYOLIC_DB_HOST: 127.0.0.1
          KYOLIC_DB_PORT: 3307
          KYOLIC_DB_DATABASE: kyolic
          KYOLIC_DB_USERNAME: root
          KYOLIC_DB_PASSWORD: secretroot
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run: vendor/bin/pest
